/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { VoloAbpHttpModelingApplicationApiDescriptionModel } from '../model/models';
import { VoloAbpHttpRemoteServiceErrorResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AbpApiDefinitionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/abp/api-definition
     * @param includeTypes 
     */
    apiAbpApiDefinitionGet(includeTypes?: boolean, extraHttpRequestParams?: any): Observable<VoloAbpHttpModelingApplicationApiDescriptionModel>;

}
