/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto } from '../model/aiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto } from '../model/aiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultSystemObject } from '../model/aiAdminInfrastructureResultSystemObject.model';
// @ts-ignore
import { AiAdminServicesAgentRolesDtosActionRuleUpsertDto } from '../model/aiAdminServicesAgentRolesDtosActionRuleUpsertDto.model';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    ActionRuleServiceInterface
} from './actionRule.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class ActionRuleService extends BaseService implements ActionRuleServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @endpoint get /admin/agent-roles/{agentRoleId}/action-rules
     * @param agentRoleId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public adminAgentRolesAgentRoleIdActionRulesGet(agentRoleId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto>;
    public adminAgentRolesAgentRoleIdActionRulesGet(agentRoleId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto>>;
    public adminAgentRolesAgentRoleIdActionRulesGet(agentRoleId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto>>;
    public adminAgentRolesAgentRoleIdActionRulesGet(agentRoleId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (agentRoleId === null || agentRoleId === undefined) {
            throw new Error('Required parameter agentRoleId was null or undefined when calling adminAgentRolesAgentRoleIdActionRulesGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/admin/agent-roles/${this.configuration.encodeParam({name: "agentRoleId", value: agentRoleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/action-rules`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint post /admin/agent-roles/{agentRoleId}/action-rules
     * @param agentRoleId 
     * @param aiAdminServicesAgentRolesDtosActionRuleUpsertDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public adminAgentRolesAgentRoleIdActionRulesPost(agentRoleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>;
    public adminAgentRolesAgentRoleIdActionRulesPost(agentRoleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>>;
    public adminAgentRolesAgentRoleIdActionRulesPost(agentRoleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>>;
    public adminAgentRolesAgentRoleIdActionRulesPost(agentRoleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (agentRoleId === null || agentRoleId === undefined) {
            throw new Error('Required parameter agentRoleId was null or undefined when calling adminAgentRolesAgentRoleIdActionRulesPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/admin/agent-roles/${this.configuration.encodeParam({name: "agentRoleId", value: agentRoleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/action-rules`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesAgentRolesDtosActionRuleUpsertDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint delete /admin/agent-roles/{agentRoleId}/action-rules/{ruleId}
     * @param agentRoleId 
     * @param ruleId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public adminAgentRolesAgentRoleIdActionRulesRuleIdDelete(agentRoleId: string, ruleId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultSystemObject>;
    public adminAgentRolesAgentRoleIdActionRulesRuleIdDelete(agentRoleId: string, ruleId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultSystemObject>>;
    public adminAgentRolesAgentRoleIdActionRulesRuleIdDelete(agentRoleId: string, ruleId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultSystemObject>>;
    public adminAgentRolesAgentRoleIdActionRulesRuleIdDelete(agentRoleId: string, ruleId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (agentRoleId === null || agentRoleId === undefined) {
            throw new Error('Required parameter agentRoleId was null or undefined when calling adminAgentRolesAgentRoleIdActionRulesRuleIdDelete.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling adminAgentRolesAgentRoleIdActionRulesRuleIdDelete.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/admin/agent-roles/${this.configuration.encodeParam({name: "agentRoleId", value: agentRoleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/action-rules/${this.configuration.encodeParam({name: "ruleId", value: ruleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultSystemObject>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint put /admin/agent-roles/{agentRoleId}/action-rules/{ruleId}
     * @param agentRoleId 
     * @param ruleId 
     * @param aiAdminServicesAgentRolesDtosActionRuleUpsertDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public adminAgentRolesAgentRoleIdActionRulesRuleIdPut(agentRoleId: string, ruleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>;
    public adminAgentRolesAgentRoleIdActionRulesRuleIdPut(agentRoleId: string, ruleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>>;
    public adminAgentRolesAgentRoleIdActionRulesRuleIdPut(agentRoleId: string, ruleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>>;
    public adminAgentRolesAgentRoleIdActionRulesRuleIdPut(agentRoleId: string, ruleId: string, aiAdminServicesAgentRolesDtosActionRuleUpsertDto?: AiAdminServicesAgentRolesDtosActionRuleUpsertDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (agentRoleId === null || agentRoleId === undefined) {
            throw new Error('Required parameter agentRoleId was null or undefined when calling adminAgentRolesAgentRoleIdActionRulesRuleIdPut.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling adminAgentRolesAgentRoleIdActionRulesRuleIdPut.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/admin/agent-roles/${this.configuration.encodeParam({name: "agentRoleId", value: agentRoleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/action-rules/${this.configuration.encodeParam({name: "ruleId", value: ruleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesAgentRolesDtosActionRuleUpsertDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
