/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo } from '../model/models';
import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataSystemObject } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminInfrastructureResultSystemString } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminUserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /admin/users/agents/{userId}
     * @param userId 
     * @param page 
     * @param limit 
     */
    adminUsersAgentsUserIdGet(userId: number, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataSystemObject>;

    /**
     * 
     * 
     * @endpoint put /admin/users/changeStatus/{status}
     * @param status 
     * @param requestBody 
     */
    adminUsersChangeStatusStatusPut(status: number, requestBody?: Array<string>, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /admin/users
     * @param mobile 
     * @param page 
     * @param limit 
     */
    adminUsersGet(mobile?: string, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo>;

    /**
     * 
     * 
     * @endpoint delete /admin/users/{id}
     * @param id 
     */
    adminUsersIdDelete(id: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint put /admin/users/{id}
     * @param id 
     */
    adminUsersIdPut(id: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemString>;

}
