/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminControllersAgentRoleRuntimeTestFinalizeRequestDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesAgentRolesAgentRoleRuntimeTestRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AgentRoleRuntimeTestServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /admin/agent-roles/runtime-test/finalize
     * @param aiAdminControllersAgentRoleRuntimeTestFinalizeRequestDto 
     */
    adminAgentRolesRuntimeTestFinalizePost(aiAdminControllersAgentRoleRuntimeTestFinalizeRequestDto?: AiAdminControllersAgentRoleRuntimeTestFinalizeRequestDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /admin/agent-roles/runtime-test
     * @param aiAdminServicesAgentRolesAgentRoleRuntimeTestRequestDto 
     */
    adminAgentRolesRuntimeTestPost(aiAdminServicesAgentRolesAgentRoleRuntimeTestRequestDto?: AiAdminServicesAgentRolesAgentRoleRuntimeTestRequestDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto>;

}
