/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminServicesAuthDtosPubConfigDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesAuthDtosTokenDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesRbacDtosUserInfoDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesAuthDtosLoginDto } from '../model/models';
import { AiAdminServicesAuthDtosPasswordDto } from '../model/models';
import { AiAdminServicesAuthDtosRegisterDto } from '../model/models';
import { AiAdminServicesAuthDtosRetrievePasswordDto } from '../model/models';
import { AiAdminServicesAuthDtosSmsVerificationDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint put /user/change-password
     * @param aiAdminServicesAuthDtosPasswordDto 
     */
    userChangePasswordPut(aiAdminServicesAuthDtosPasswordDto?: AiAdminServicesAuthDtosPasswordDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /user/info
     */
    userInfoGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesRbacDtosUserInfoDto>;

    /**
     * 
     * 
     * @endpoint post /user/login
     * @param aiAdminServicesAuthDtosLoginDto 
     */
    userLoginPost(aiAdminServicesAuthDtosLoginDto?: AiAdminServicesAuthDtosLoginDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesAuthDtosTokenDto>;

    /**
     * 
     * 
     * @endpoint get /user/pub-config
     */
    userPubConfigGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesAuthDtosPubConfigDto>;

    /**
     * 
     * 
     * @endpoint post /user/register
     * @param aiAdminServicesAuthDtosRegisterDto 
     */
    userRegisterPost(aiAdminServicesAuthDtosRegisterDto?: AiAdminServicesAuthDtosRegisterDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint put /user/retrieve-password
     * @param aiAdminServicesAuthDtosRetrievePasswordDto 
     */
    userRetrievePasswordPut(aiAdminServicesAuthDtosRetrievePasswordDto?: AiAdminServicesAuthDtosRetrievePasswordDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /user/smsVerification
     * @param aiAdminServicesAuthDtosSmsVerificationDto 
     */
    userSmsVerificationPost(aiAdminServicesAuthDtosSmsVerificationDto?: AiAdminServicesAuthDtosSmsVerificationDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

}
