/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderDetailDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderPayResultDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingSummaryDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingUsageReportResultDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesBillingDtosBillingPlanItemDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesBillingDtosBillingOrderPayDto } from '../model/models';
import { AiAdminServicesBillingDtosBillingUsageReportDto } from '../model/models';
import { AiAdminServicesBillingDtosCreateBillingOrderDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BillingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /billing/me/summary
     */
    billingMeSummaryGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingSummaryDto>;

    /**
     * 
     * 
     * @endpoint get /billing/orders
     * @param status 
     * @param page 
     * @param limit 
     */
    billingOrdersGet(status?: string, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto>;

    /**
     * 
     * 
     * @endpoint post /billing/orders/{id}/cancel
     * @param id 
     */
    billingOrdersIdCancelPost(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /billing/orders/{id}
     * @param id 
     */
    billingOrdersIdGet(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderDetailDto>;

    /**
     * 
     * 
     * @endpoint post /billing/orders/{id}/pay
     * @param id 
     * @param aiAdminServicesBillingDtosBillingOrderPayDto 
     */
    billingOrdersIdPayPost(id: string, aiAdminServicesBillingDtosBillingOrderPayDto?: AiAdminServicesBillingDtosBillingOrderPayDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderPayResultDto>;

    /**
     * 
     * 
     * @endpoint post /billing/orders
     * @param aiAdminServicesBillingDtosCreateBillingOrderDto 
     */
    billingOrdersPost(aiAdminServicesBillingDtosCreateBillingOrderDto?: AiAdminServicesBillingDtosCreateBillingOrderDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderDetailDto>;

    /**
     * 
     * 
     * @endpoint get /billing/plans
     */
    billingPlansGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesBillingDtosBillingPlanItemDto>;

    /**
     * 
     * 
     * @endpoint post /billing/usage/report
     * @param aiAdminServicesBillingDtosBillingUsageReportDto 
     */
    billingUsageReportPost(aiAdminServicesBillingDtosBillingUsageReportDto?: AiAdminServicesBillingDtosBillingUsageReportDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingUsageReportResultDto>;

}
