/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBindingConfigsDtosBindingConfigDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesBindingConfigsDtosBindingConfigDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosOptionItemDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesBindingConfigsDtosBindingConfigKindMetaDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesBindingConfigsDtosBindingConfigUpsertDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BindingConfigServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /admin/binding-configs/integration-options
     * @param providerCode 
     * @param scope 
     */
    adminBindingConfigsIntegrationOptionsGet(providerCode?: string, scope?: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosOptionItemDto>;

    /**
     * 
     * 
     * @endpoint get /admin/binding-configs/{kind}
     * @param kind 
     * @param keyword 
     * @param status 
     * @param page 
     * @param limit 
     */
    adminBindingConfigsKindGet(kind: string, keyword?: string, status?: string, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBindingConfigsDtosBindingConfigDto>;

    /**
     * 
     * 
     * @endpoint delete /admin/binding-configs/{kind}/{id}
     * @param kind 
     * @param id 
     */
    adminBindingConfigsKindIdDelete(kind: string, id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /admin/binding-configs/{kind}/{id}
     * @param kind 
     * @param id 
     */
    adminBindingConfigsKindIdGet(kind: string, id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBindingConfigsDtosBindingConfigDto>;

    /**
     * 
     * 
     * @endpoint put /admin/binding-configs/{kind}/{id}
     * @param kind 
     * @param id 
     * @param aiAdminServicesBindingConfigsDtosBindingConfigUpsertDto 
     */
    adminBindingConfigsKindIdPut(kind: string, id: string, aiAdminServicesBindingConfigsDtosBindingConfigUpsertDto?: AiAdminServicesBindingConfigsDtosBindingConfigUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBindingConfigsDtosBindingConfigDto>;

    /**
     * 
     * 
     * @endpoint post /admin/binding-configs/{kind}
     * @param kind 
     * @param aiAdminServicesBindingConfigsDtosBindingConfigUpsertDto 
     */
    adminBindingConfigsKindPost(kind: string, aiAdminServicesBindingConfigsDtosBindingConfigUpsertDto?: AiAdminServicesBindingConfigsDtosBindingConfigUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesBindingConfigsDtosBindingConfigDto>;

    /**
     * 
     * 
     * @endpoint get /admin/binding-configs/kinds
     */
    adminBindingConfigsKindsGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesBindingConfigsDtosBindingConfigKindMetaDto>;

}
