/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultSystemObject } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConfigServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /config/server-base
     */
    configServerBasePost(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

}
