/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosAsrRecognitionResponseDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosConversationExecutionBindingDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosLlmChatResponseDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationPlanDto } from '../model/models';
import { AiAdminServicesRuntimeExecutionDtosConversationAsrExecutionRequestDto } from '../model/models';
import { AiAdminServicesRuntimeExecutionDtosConversationLlmExecutionRequestDto } from '../model/models';
import { AiAdminServicesRuntimeExecutionDtosConversationTtsExecutionRequestDto } from '../model/models';
import { AiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConversationOrchestrationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /admin/runtime/orchestration/asr/recognize
     * @param aiAdminServicesRuntimeExecutionDtosConversationAsrExecutionRequestDto 
     */
    adminRuntimeOrchestrationAsrRecognizePost(aiAdminServicesRuntimeExecutionDtosConversationAsrExecutionRequestDto?: AiAdminServicesRuntimeExecutionDtosConversationAsrExecutionRequestDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosAsrRecognitionResponseDto>;

    /**
     * 
     * 
     * @endpoint post /admin/runtime/orchestration/binding
     * @param aiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto 
     */
    adminRuntimeOrchestrationBindingPost(aiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto?: AiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosConversationExecutionBindingDto>;

    /**
     * 
     * 
     * @endpoint post /admin/runtime/orchestration/llm/chat
     * @param aiAdminServicesRuntimeExecutionDtosConversationLlmExecutionRequestDto 
     */
    adminRuntimeOrchestrationLlmChatPost(aiAdminServicesRuntimeExecutionDtosConversationLlmExecutionRequestDto?: AiAdminServicesRuntimeExecutionDtosConversationLlmExecutionRequestDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosLlmChatResponseDto>;

    /**
     * 
     * 
     * @endpoint post /admin/runtime/orchestration/plan
     * @param aiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto 
     */
    adminRuntimeOrchestrationPlanPost(aiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto?: AiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationPlanDto>;

    /**
     * 
     * 
     * @endpoint post /admin/runtime/orchestration/tts/synthesize
     * @param aiAdminServicesRuntimeExecutionDtosConversationTtsExecutionRequestDto 
     */
    adminRuntimeOrchestrationTtsSynthesizePost(aiAdminServicesRuntimeExecutionDtosConversationTtsExecutionRequestDto?: AiAdminServicesRuntimeExecutionDtosConversationTtsExecutionRequestDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto>;

}
