/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesDeviceDtosUserShowDeviceListVo } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesDeviceDtosDeviceBootstrapStatusDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesDeviceDtosDeviceProvisioningCredentialDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesDeviceDtosIotDeviceDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesDeviceDtosIotDeviceDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListSystemObject } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesDeviceDtosDeviceManualAddDto } from '../model/models';
import { AiAdminServicesDeviceDtosDeviceProvisioningIssueDto } from '../model/models';
import { AiAdminServicesDeviceDtosDeviceReportDto } from '../model/models';
import { AiAdminServicesDeviceDtosDeviceToolsCallReqDto } from '../model/models';
import { AiAdminServicesDeviceDtosDeviceUnBindDto } from '../model/models';
import { AiAdminServicesDeviceDtosDeviceUpdateDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DeviceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /admin/device/all
     * @param keywords 
     * @param page 
     * @param limit 
     */
    adminDeviceAllGet(keywords?: string, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesDeviceDtosUserShowDeviceListVo>;

    /**
     * 
     * 
     * @endpoint post /device/bootstrap
     */
    deviceBootstrapPost(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesDeviceDtosDeviceBootstrapStatusDto>;

    /**
     * 
     * 
     * @endpoint delete /device/{id}
     * @param id 
     */
    deviceIdDelete(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /device/{id}
     * @param id 
     */
    deviceIdGet(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesDeviceDtosIotDeviceDto>;

    /**
     * 
     * 
     * @endpoint put /device/{id}
     * @param id 
     * @param aiAdminServicesDeviceDtosDeviceUpdateDto 
     */
    deviceIdPut(id: string, aiAdminServicesDeviceDtosDeviceUpdateDto?: AiAdminServicesDeviceDtosDeviceUpdateDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /device/list
     */
    deviceListGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesDeviceDtosIotDeviceDto>;

    /**
     * 
     * 
     * @endpoint post /device/manual-add
     * @param aiAdminServicesDeviceDtosDeviceManualAddDto 
     */
    deviceManualAddPost(aiAdminServicesDeviceDtosDeviceManualAddDto?: AiAdminServicesDeviceDtosDeviceManualAddDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /device/provisioning/issue
     * @param aiAdminServicesDeviceDtosDeviceProvisioningIssueDto 
     */
    deviceProvisioningIssuePost(aiAdminServicesDeviceDtosDeviceProvisioningIssueDto?: AiAdminServicesDeviceDtosDeviceProvisioningIssueDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesDeviceDtosDeviceProvisioningCredentialDto>;

    /**
     * 
     * 
     * @endpoint post /device/tools/call/{deviceId}
     * @param deviceId 
     * @param aiAdminServicesDeviceDtosDeviceToolsCallReqDto 
     */
    deviceToolsCallDeviceIdPost(deviceId: string, aiAdminServicesDeviceDtosDeviceToolsCallReqDto?: AiAdminServicesDeviceDtosDeviceToolsCallReqDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /device/tools/list/{deviceId}
     * @param deviceId 
     */
    deviceToolsListDeviceIdPost(deviceId: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListSystemObject>;

    /**
     * 
     * 
     * @endpoint post /device/unbind
     * @param aiAdminServicesDeviceDtosDeviceUnBindDto 
     */
    deviceUnbindPost(aiAdminServicesDeviceDtosDeviceUnBindDto?: AiAdminServicesDeviceDtosDeviceUnBindDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint put /device/update/{id}
     * @param id 
     * @param aiAdminServicesDeviceDtosDeviceUpdateDto 
     */
    deviceUpdateIdPut(id: string, aiAdminServicesDeviceDtosDeviceUpdateDto?: AiAdminServicesDeviceDtosDeviceUpdateDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /ota
     * @param deviceId 
     * @param aiAdminServicesDeviceDtosDeviceReportDto 
     */
    otaPost(deviceId?: string, aiAdminServicesDeviceDtosDeviceReportDto?: AiAdminServicesDeviceDtosDeviceReportDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

}
