/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMcpToolsDtosMcpToolDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesMcpToolsDtosMcpToolDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMcpToolsDtosMcpToolOptionDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListSystemString } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesMcpToolsDtosMcpToolUpsertDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface McpToolServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /admin/mcp-tools/categories
     */
    adminMcpToolsCategoriesGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListSystemString>;

    /**
     * 
     * 
     * @endpoint get /admin/mcp-tools
     * @param page 
     * @param limit 
     * @param keyword 
     * @param status 
     * @param category 
     */
    adminMcpToolsGet(page?: number, limit?: number, keyword?: string, status?: string, category?: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMcpToolsDtosMcpToolDto>;

    /**
     * 
     * 
     * @endpoint delete /admin/mcp-tools/{id}
     * @param id 
     */
    adminMcpToolsIdDelete(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /admin/mcp-tools/{id}
     * @param id 
     */
    adminMcpToolsIdGet(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMcpToolsDtosMcpToolDto>;

    /**
     * 
     * 
     * @endpoint put /admin/mcp-tools/{id}
     * @param id 
     * @param aiAdminServicesMcpToolsDtosMcpToolUpsertDto 
     */
    adminMcpToolsIdPut(id: string, aiAdminServicesMcpToolsDtosMcpToolUpsertDto?: AiAdminServicesMcpToolsDtosMcpToolUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMcpToolsDtosMcpToolDto>;

    /**
     * 
     * 
     * @endpoint get /admin/mcp-tools/options
     */
    adminMcpToolsOptionsGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMcpToolsDtosMcpToolOptionDto>;

    /**
     * 
     * 
     * @endpoint post /admin/mcp-tools
     * @param aiAdminServicesMcpToolsDtosMcpToolUpsertDto 
     */
    adminMcpToolsPost(aiAdminServicesMcpToolsDtosMcpToolUpsertDto?: AiAdminServicesMcpToolsDtosMcpToolUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMcpToolsDtosMcpToolDto>;

}
