/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto } from '../model/aiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto } from '../model/aiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto } from '../model/aiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto } from '../model/aiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto } from '../model/aiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto } from '../model/aiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto } from '../model/aiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto.model';
// @ts-ignore
import { AiAdminInfrastructureResultSystemObject } from '../model/aiAdminInfrastructureResultSystemObject.model';
// @ts-ignore
import { AiAdminServicesMemoryDtosMemoryRecordUpsertDto } from '../model/aiAdminServicesMemoryDtosMemoryRecordUpsertDto.model';
// @ts-ignore
import { AiAdminServicesMemoryDtosMemoryRuleUpsertDto } from '../model/aiAdminServicesMemoryDtosMemoryRuleUpsertDto.model';
// @ts-ignore
import { AiAdminServicesMemoryDtosMemorySearchDto } from '../model/aiAdminServicesMemoryDtosMemorySearchDto.model';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    MemoryLibraryServiceInterface
} from './memoryLibrary.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class MemoryLibraryService extends BaseService implements MemoryLibraryServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @endpoint get /memory-libraries
     * @param page 
     * @param limit 
     * @param keyword 
     * @param agentId 
     * @param status 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesGet(page?: number, limit?: number, keyword?: string, agentId?: string, status?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto>;
    public memoryLibrariesGet(page?: number, limit?: number, keyword?: string, agentId?: string, status?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto>>;
    public memoryLibrariesGet(page?: number, limit?: number, keyword?: string, agentId?: string, status?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto>>;
    public memoryLibrariesGet(page?: number, limit?: number, keyword?: string, agentId?: string, status?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'Page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'Limit',
            <any>limit,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'Keyword',
            <any>keyword,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'AgentId',
            <any>agentId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'Status',
            <any>status,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /memory-libraries/{id}
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesIdGet(id: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto>;
    public memoryLibrariesIdGet(id: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto>>;
    public memoryLibrariesIdGet(id: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto>>;
    public memoryLibrariesIdGet(id: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling memoryLibrariesIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /memory-libraries/{libraryId}/records
     * @param libraryId 
     * @param page 
     * @param limit 
     * @param recordType 
     * @param keyword 
     * @param includeExpired 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRecordsGet(libraryId: string, page?: number, limit?: number, recordType?: string, keyword?: string, includeExpired?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto>;
    public memoryLibrariesLibraryIdRecordsGet(libraryId: string, page?: number, limit?: number, recordType?: string, keyword?: string, includeExpired?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsGet(libraryId: string, page?: number, limit?: number, recordType?: string, keyword?: string, includeExpired?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsGet(libraryId: string, page?: number, limit?: number, recordType?: string, keyword?: string, includeExpired?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRecordsGet.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'Page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'Limit',
            <any>limit,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'RecordType',
            <any>recordType,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'Keyword',
            <any>keyword,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'IncludeExpired',
            <any>includeExpired,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/records`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint post /memory-libraries/{libraryId}/records/ingest
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemoryRecordUpsertDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRecordsIngestPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>;
    public memoryLibrariesLibraryIdRecordsIngestPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsIngestPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsIngestPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRecordsIngestPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/records/ingest`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesMemoryDtosMemoryRecordUpsertDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint post /memory-libraries/{libraryId}/records
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemoryRecordUpsertDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRecordsPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>;
    public memoryLibrariesLibraryIdRecordsPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRecordsPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/records`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesMemoryDtosMemoryRecordUpsertDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint delete /memory-libraries/{libraryId}/records/{recordId}
     * @param libraryId 
     * @param recordId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRecordsRecordIdDelete(libraryId: string, recordId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultSystemObject>;
    public memoryLibrariesLibraryIdRecordsRecordIdDelete(libraryId: string, recordId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultSystemObject>>;
    public memoryLibrariesLibraryIdRecordsRecordIdDelete(libraryId: string, recordId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultSystemObject>>;
    public memoryLibrariesLibraryIdRecordsRecordIdDelete(libraryId: string, recordId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRecordsRecordIdDelete.');
        }
        if (recordId === null || recordId === undefined) {
            throw new Error('Required parameter recordId was null or undefined when calling memoryLibrariesLibraryIdRecordsRecordIdDelete.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/records/${this.configuration.encodeParam({name: "recordId", value: recordId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultSystemObject>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint put /memory-libraries/{libraryId}/records/{recordId}
     * @param libraryId 
     * @param recordId 
     * @param aiAdminServicesMemoryDtosMemoryRecordUpsertDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRecordsRecordIdPut(libraryId: string, recordId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>;
    public memoryLibrariesLibraryIdRecordsRecordIdPut(libraryId: string, recordId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsRecordIdPut(libraryId: string, recordId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>>;
    public memoryLibrariesLibraryIdRecordsRecordIdPut(libraryId: string, recordId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRecordsRecordIdPut.');
        }
        if (recordId === null || recordId === undefined) {
            throw new Error('Required parameter recordId was null or undefined when calling memoryLibrariesLibraryIdRecordsRecordIdPut.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/records/${this.configuration.encodeParam({name: "recordId", value: recordId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesMemoryDtosMemoryRecordUpsertDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint post /memory-libraries/{libraryId}/records/search
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemorySearchDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRecordsSearchPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>;
    public memoryLibrariesLibraryIdRecordsSearchPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>>;
    public memoryLibrariesLibraryIdRecordsSearchPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>>;
    public memoryLibrariesLibraryIdRecordsSearchPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRecordsSearchPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/records/search`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesMemoryDtosMemorySearchDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint post /memory-libraries/{libraryId}/retrieval-test
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemorySearchDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRetrievalTestPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>;
    public memoryLibrariesLibraryIdRetrievalTestPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>>;
    public memoryLibrariesLibraryIdRetrievalTestPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>>;
    public memoryLibrariesLibraryIdRetrievalTestPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRetrievalTestPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/retrieval-test`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesMemoryDtosMemorySearchDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /memory-libraries/{libraryId}/rules
     * @param libraryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRulesGet(libraryId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto>;
    public memoryLibrariesLibraryIdRulesGet(libraryId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto>>;
    public memoryLibrariesLibraryIdRulesGet(libraryId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto>>;
    public memoryLibrariesLibraryIdRulesGet(libraryId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRulesGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/rules`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint post /memory-libraries/{libraryId}/rules
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemoryRuleUpsertDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRulesPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>;
    public memoryLibrariesLibraryIdRulesPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>>;
    public memoryLibrariesLibraryIdRulesPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>>;
    public memoryLibrariesLibraryIdRulesPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRulesPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/rules`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesMemoryDtosMemoryRuleUpsertDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint delete /memory-libraries/{libraryId}/rules/{ruleId}
     * @param libraryId 
     * @param ruleId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRulesRuleIdDelete(libraryId: string, ruleId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultSystemObject>;
    public memoryLibrariesLibraryIdRulesRuleIdDelete(libraryId: string, ruleId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultSystemObject>>;
    public memoryLibrariesLibraryIdRulesRuleIdDelete(libraryId: string, ruleId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultSystemObject>>;
    public memoryLibrariesLibraryIdRulesRuleIdDelete(libraryId: string, ruleId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRulesRuleIdDelete.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling memoryLibrariesLibraryIdRulesRuleIdDelete.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/rules/${this.configuration.encodeParam({name: "ruleId", value: ruleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultSystemObject>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint put /memory-libraries/{libraryId}/rules/{ruleId}
     * @param libraryId 
     * @param ruleId 
     * @param aiAdminServicesMemoryDtosMemoryRuleUpsertDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public memoryLibrariesLibraryIdRulesRuleIdPut(libraryId: string, ruleId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>;
    public memoryLibrariesLibraryIdRulesRuleIdPut(libraryId: string, ruleId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>>;
    public memoryLibrariesLibraryIdRulesRuleIdPut(libraryId: string, ruleId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>>;
    public memoryLibrariesLibraryIdRulesRuleIdPut(libraryId: string, ruleId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (libraryId === null || libraryId === undefined) {
            throw new Error('Required parameter libraryId was null or undefined when calling memoryLibrariesLibraryIdRulesRuleIdPut.');
        }
        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling memoryLibrariesLibraryIdRulesRuleIdPut.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/memory-libraries/${this.configuration.encodeParam({name: "libraryId", value: libraryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/rules/${this.configuration.encodeParam({name: "ruleId", value: ruleId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: aiAdminServicesMemoryDtosMemoryRuleUpsertDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
