/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesMemoryDtosMemoryRecordUpsertDto } from '../model/models';
import { AiAdminServicesMemoryDtosMemoryRuleUpsertDto } from '../model/models';
import { AiAdminServicesMemoryDtosMemorySearchDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MemoryLibraryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /memory-libraries
     * @param page 
     * @param limit 
     * @param keyword 
     * @param agentId 
     * @param status 
     */
    memoryLibrariesGet(page?: number, limit?: number, keyword?: string, agentId?: string, status?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto>;

    /**
     * 
     * 
     * @endpoint get /memory-libraries/{id}
     * @param id 
     */
    memoryLibrariesIdGet(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto>;

    /**
     * 
     * 
     * @endpoint get /memory-libraries/{libraryId}/records
     * @param libraryId 
     * @param page 
     * @param limit 
     * @param recordType 
     * @param keyword 
     * @param includeExpired 
     */
    memoryLibrariesLibraryIdRecordsGet(libraryId: string, page?: number, limit?: number, recordType?: string, keyword?: string, includeExpired?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto>;

    /**
     * 
     * 
     * @endpoint post /memory-libraries/{libraryId}/records/ingest
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemoryRecordUpsertDto 
     */
    memoryLibrariesLibraryIdRecordsIngestPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>;

    /**
     * 
     * 
     * @endpoint post /memory-libraries/{libraryId}/records
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemoryRecordUpsertDto 
     */
    memoryLibrariesLibraryIdRecordsPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>;

    /**
     * 
     * 
     * @endpoint delete /memory-libraries/{libraryId}/records/{recordId}
     * @param libraryId 
     * @param recordId 
     */
    memoryLibrariesLibraryIdRecordsRecordIdDelete(libraryId: string, recordId: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint put /memory-libraries/{libraryId}/records/{recordId}
     * @param libraryId 
     * @param recordId 
     * @param aiAdminServicesMemoryDtosMemoryRecordUpsertDto 
     */
    memoryLibrariesLibraryIdRecordsRecordIdPut(libraryId: string, recordId: string, aiAdminServicesMemoryDtosMemoryRecordUpsertDto?: AiAdminServicesMemoryDtosMemoryRecordUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto>;

    /**
     * 
     * 
     * @endpoint post /memory-libraries/{libraryId}/records/search
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemorySearchDto 
     */
    memoryLibrariesLibraryIdRecordsSearchPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>;

    /**
     * 
     * 
     * @endpoint post /memory-libraries/{libraryId}/retrieval-test
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemorySearchDto 
     */
    memoryLibrariesLibraryIdRetrievalTestPost(libraryId: string, aiAdminServicesMemoryDtosMemorySearchDto?: AiAdminServicesMemoryDtosMemorySearchDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto>;

    /**
     * 
     * 
     * @endpoint get /memory-libraries/{libraryId}/rules
     * @param libraryId 
     */
    memoryLibrariesLibraryIdRulesGet(libraryId: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto>;

    /**
     * 
     * 
     * @endpoint post /memory-libraries/{libraryId}/rules
     * @param libraryId 
     * @param aiAdminServicesMemoryDtosMemoryRuleUpsertDto 
     */
    memoryLibrariesLibraryIdRulesPost(libraryId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>;

    /**
     * 
     * 
     * @endpoint delete /memory-libraries/{libraryId}/rules/{ruleId}
     * @param libraryId 
     * @param ruleId 
     */
    memoryLibrariesLibraryIdRulesRuleIdDelete(libraryId: string, ruleId: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint put /memory-libraries/{libraryId}/rules/{ruleId}
     * @param libraryId 
     * @param ruleId 
     * @param aiAdminServicesMemoryDtosMemoryRuleUpsertDto 
     */
    memoryLibrariesLibraryIdRulesRuleIdPut(libraryId: string, ruleId: string, aiAdminServicesMemoryDtosMemoryRuleUpsertDto?: AiAdminServicesMemoryDtosMemoryRuleUpsertDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto>;

}
