/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesVoiceDtosOtaEntityDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminInfrastructureResultSystemString } from '../model/models';
import { AiAdminServicesVoiceDtosOtaEntityDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OtaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /otaMag/batch/{ids}
     * @param ids 
     */
    otaMagBatchIdsDelete(ids: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /otaMag/download/{uuid}
     * @param uuid 
     */
    otaMagDownloadUuidGet(uuid: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /otaMag
     * @param page 
     * @param limit 
     */
    otaMagGet(page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto>;

    /**
     * 
     * 
     * @endpoint get /otaMag/getDownloadUrl/{id}
     * @param id 
     */
    otaMagGetDownloadUrlIdGet(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemString>;

    /**
     * 
     * 
     * @endpoint get /otaMag/{id}
     * @param id 
     */
    otaMagIdGet(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesVoiceDtosOtaEntityDto>;

    /**
     * 
     * 
     * @endpoint put /otaMag/{id}
     * @param id 
     * @param aiAdminServicesVoiceDtosOtaEntityDto 
     */
    otaMagIdPut(id: string, aiAdminServicesVoiceDtosOtaEntityDto?: AiAdminServicesVoiceDtosOtaEntityDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /otaMag
     * @param aiAdminServicesVoiceDtosOtaEntityDto 
     */
    otaMagPost(aiAdminServicesVoiceDtosOtaEntityDto?: AiAdminServicesVoiceDtosOtaEntityDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /otaMag/uploadAssetsBin
     * @param file 
     */
    otaMagUploadAssetsBinPost(file?: Blob, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemString>;

    /**
     * 
     * 
     * @endpoint post /otaMag/upload
     * @param file 
     */
    otaMagUploadPost(file?: Blob, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemString>;

}
