/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesRbacDtosRoleDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosMenuTreeDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosRoleDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListSystemInt64 } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesRbacDtosRoleCreateDto } from '../model/models';
import { AiAdminServicesRbacDtosRoleMenuAssignDto } from '../model/models';
import { AiAdminServicesRbacDtosRoleUpdateDto } from '../model/models';
import { AiAdminServicesRbacDtosUserRoleAssignDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /system/roles/all
     */
    systemRolesAllGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosRoleDto>;

    /**
     * 
     * 
     * @endpoint get /system/roles
     * @param name 
     * @param page 
     * @param limit 
     */
    systemRolesGet(name?: string, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesRbacDtosRoleDto>;

    /**
     * 
     * 
     * @endpoint delete /system/roles/{id}
     * @param id 
     */
    systemRolesIdDelete(id: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /system/roles/{id}/menus
     * @param id 
     */
    systemRolesIdMenusGet(id: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListSystemInt64>;

    /**
     * 
     * 
     * @endpoint put /system/roles/{id}/menus
     * @param id 
     * @param aiAdminServicesRbacDtosRoleMenuAssignDto 
     */
    systemRolesIdMenusPut(id: number, aiAdminServicesRbacDtosRoleMenuAssignDto?: AiAdminServicesRbacDtosRoleMenuAssignDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint put /system/roles/{id}
     * @param id 
     * @param aiAdminServicesRbacDtosRoleUpdateDto 
     */
    systemRolesIdPut(id: number, aiAdminServicesRbacDtosRoleUpdateDto?: AiAdminServicesRbacDtosRoleUpdateDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /system/roles/menu-tree
     */
    systemRolesMenuTreeGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosMenuTreeDto>;

    /**
     * 
     * 
     * @endpoint post /system/roles
     * @param aiAdminServicesRbacDtosRoleCreateDto 
     */
    systemRolesPost(aiAdminServicesRbacDtosRoleCreateDto?: AiAdminServicesRbacDtosRoleCreateDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /system/roles/user/{userId}
     * @param userId 
     */
    systemRolesUserUserIdGet(userId: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListSystemInt64>;

    /**
     * 
     * 
     * @endpoint put /system/roles/user/{userId}
     * @param userId 
     * @param aiAdminServicesRbacDtosUserRoleAssignDto 
     */
    systemRolesUserUserIdPut(userId: number, aiAdminServicesRbacDtosUserRoleAssignDto?: AiAdminServicesRbacDtosUserRoleAssignDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

}
