/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminControllersRuntimeStatusDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ServerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /admin/server/runtime-status
     */
    adminServerRuntimeStatusGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminControllersRuntimeStatusDto>;

}
