/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminServicesAdminDtosAdminSystemSettingsDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesAdminDtosAdminSystemSettingsDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SystemSettingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /admin/params/settings
     */
    adminParamsSettingsGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesAdminDtosAdminSystemSettingsDto>;

    /**
     * 
     * 
     * @endpoint put /admin/params/settings
     * @param aiAdminServicesAdminDtosAdminSystemSettingsDto 
     */
    adminParamsSettingsPut(aiAdminServicesAdminDtosAdminSystemSettingsDto?: AiAdminServicesAdminDtosAdminSystemSettingsDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

}
