/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesVoiceDtosTimbreDetailsVo } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesVoiceDtosTimbreDetailsVo } from '../model/models';
import { AiAdminInfrastructureResultAiAdminServicesVoiceDtosTtsVoiceSyncResultDto } from '../model/models';
import { AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesVoiceDtosTtsProfileOptionDto } from '../model/models';
import { AiAdminInfrastructureResultSystemObject } from '../model/models';
import { AiAdminServicesVoiceDtosTimbreDataDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TtsVoiceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /ttsVoice/delete
     * @param requestBody 
     */
    ttsVoiceDeletePost(requestBody?: Array<string>, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint get /ttsVoice
     * @param ttsProfileId 
     * @param name 
     * @param page 
     * @param limit 
     */
    ttsVoiceGet(ttsProfileId?: string, name?: string, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesVoiceDtosTimbreDetailsVo>;

    /**
     * 
     * 
     * @endpoint get /ttsVoice/{id}
     * @param id 
     */
    ttsVoiceIdGet(id: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesVoiceDtosTimbreDetailsVo>;

    /**
     * 
     * 
     * @endpoint put /ttsVoice/{id}
     * @param id 
     * @param aiAdminServicesVoiceDtosTimbreDataDto 
     */
    ttsVoiceIdPut(id: string, aiAdminServicesVoiceDtosTimbreDataDto?: AiAdminServicesVoiceDtosTimbreDataDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /ttsVoice
     * @param aiAdminServicesVoiceDtosTimbreDataDto 
     */
    ttsVoicePost(aiAdminServicesVoiceDtosTimbreDataDto?: AiAdminServicesVoiceDtosTimbreDataDto, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemObject>;

    /**
     * 
     * 
     * @endpoint post /ttsVoice/sync/{ttsProfileId}
     * @param ttsProfileId 
     */
    ttsVoiceSyncTtsProfileIdPost(ttsProfileId: string, extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultAiAdminServicesVoiceDtosTtsVoiceSyncResultDto>;

    /**
     * 
     * 
     * @endpoint get /ttsVoice/tts-profile-options
     */
    ttsVoiceTtsProfileOptionsGet(extraHttpRequestParams?: any): Observable<AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesVoiceDtosTtsProfileOptionDto>;

}
