//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_import

import 'package:one_of_serializer/any_of_serializer.dart';
import 'package:one_of_serializer/one_of_serializer.dart';
import 'package:built_collection/built_collection.dart';
import 'package:built_value/json_object.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';
import 'package:built_value/iso_8601_date_time_serializer.dart';
import 'package:openapi/src/date_serializer.dart';
import 'package:openapi/src/model/date.dart';

import 'package:openapi/src/model/ai_admin_controllers_agent_role_runtime_test_finalize_request_dto.dart';
import 'package:openapi/src/model/ai_admin_controllers_create_todo_dto.dart';
import 'package:openapi/src/model/ai_admin_controllers_device_status_request.dart';
import 'package:openapi/src/model/ai_admin_controllers_runtime_service_status_dto.dart';
import 'package:openapi/src/model/ai_admin_controllers_runtime_status_dto.dart';
import 'package:openapi/src/model/ai_admin_entities_provider_type.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_admin_dtos_admin_page_user_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_admin_dtos_audit_log_page_item_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_agent_roles_dtos_agent_role_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_admin_billing_order_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_admin_billing_subscription_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_admin_billing_usage_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_billing_order_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_binding_configs_dtos_binding_config_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_device_dtos_user_show_device_list_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_knowledge_dtos_knowledge_base_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_knowledge_dtos_knowledge_files_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_mcp_tools_dtos_mcp_tool_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_memory_dtos_memory_library_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_memory_dtos_memory_record_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_memory_dtos_runtime_signal_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_rbac_dtos_role_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_voice_dtos_ota_entity_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_ai_admin_services_voice_dtos_timbre_details_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_page_data_system_object.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_controllers_runtime_status_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_admin_dtos_admin_page_user_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_admin_dtos_audit_log_page_item_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_agent_roles_dtos_agent_role_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_admin_billing_order_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_admin_billing_subscription_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_admin_billing_usage_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_billing_dtos_billing_order_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_binding_configs_dtos_binding_config_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_device_dtos_user_show_device_list_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_knowledge_dtos_knowledge_base_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_knowledge_dtos_knowledge_files_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_mcp_tools_dtos_mcp_tool_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_memory_dtos_memory_library_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_memory_dtos_memory_record_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_memory_dtos_runtime_signal_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_rbac_dtos_role_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_voice_dtos_ota_entity_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_ai_admin_services_voice_dtos_timbre_details_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_infrastructure_page_data_system_object.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_admin_dtos_admin_system_settings_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_agent_roles_agent_role_runtime_test_result_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_agent_roles_dtos_action_rule_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_agent_roles_dtos_agent_role_binding_options_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_agent_roles_dtos_agent_role_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_agent_roles_dtos_agent_role_release_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_auth_dtos_pub_config_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_auth_dtos_token_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_billing_dtos_billing_order_detail_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_billing_dtos_billing_order_pay_result_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_billing_dtos_billing_summary_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_billing_dtos_billing_usage_report_result_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_binding_configs_dtos_binding_config_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_device_dtos_device_bootstrap_status_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_device_dtos_device_provisioning_credential_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_device_dtos_iot_device_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_knowledge_dtos_knowledge_base_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_knowledge_dtos_knowledge_files_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_knowledge_dtos_list_vo_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_knowledge_dtos_result_vo_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_mcp_tools_dtos_mcp_tool_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_memory_dtos_memory_library_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_memory_dtos_memory_record_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_memory_dtos_memory_rule_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_memory_dtos_memory_search_result_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_memory_dtos_runtime_signal_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_rbac_dtos_user_info_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_runtime_execution_dtos_asr_recognition_response_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_runtime_execution_dtos_conversation_execution_binding_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_runtime_execution_dtos_llm_chat_response_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_runtime_execution_dtos_tts_synthesis_response_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_runtime_orchestration_dtos_conversation_orchestration_plan_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_voice_dtos_ota_entity_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_voice_dtos_timbre_details_vo.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_ai_admin_services_voice_dtos_tts_voice_sync_result_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_agent_roles_dtos_action_rule_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_agent_roles_dtos_agent_role_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_agent_roles_dtos_agent_role_release_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_agent_roles_dtos_option_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_billing_dtos_billing_plan_item_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_binding_configs_dtos_binding_config_kind_meta_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_device_dtos_iot_device_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_mcp_tools_dtos_mcp_tool_option_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_memory_dtos_memory_rule_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_rbac_dtos_menu_tree_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_rbac_dtos_role_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_ai_admin_services_voice_dtos_tts_profile_option_dto.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_system_int64.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_system_object.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_collections_generic_list_system_string.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_object.dart';
import 'package:openapi/src/model/ai_admin_infrastructure_result_system_string.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_admin_page_user_vo.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_admin_system_billing_settings_dto.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_admin_system_log_settings_dto.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_admin_system_runtime_settings_dto.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_admin_system_server_settings_dto.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_admin_system_settings_dto.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_audit_entity_change_vo.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_audit_log_action_vo.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_audit_log_page_item_vo.dart';
import 'package:openapi/src/model/ai_admin_services_admin_dtos_audit_property_change_vo.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_agent_role_runtime_test_knowledge_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_agent_role_runtime_test_knowledge_hit_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_agent_role_runtime_test_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_agent_role_runtime_test_result_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_agent_role_runtime_test_stage_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_action_rule_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_action_rule_upsert_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_binding_options_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_context_provider_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_knowledge_binding_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_plugin_mapping_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_publish_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_release_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_agent_role_upsert_dto.dart';
import 'package:openapi/src/model/ai_admin_services_agent_roles_dtos_option_item_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_login_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_menu_item_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_password_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_pub_config_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_register_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_retrieve_password_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_sms_verification_dto.dart';
import 'package:openapi/src/model/ai_admin_services_auth_dtos_token_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_admin_billing_order_item_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_admin_billing_subscription_item_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_admin_billing_usage_item_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_admin_mark_order_paid_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_order_detail_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_order_item_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_order_pay_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_order_pay_result_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_plan_item_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_summary_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_usage_report_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_billing_usage_report_result_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_create_billing_order_dto.dart';
import 'package:openapi/src/model/ai_admin_services_billing_dtos_manual_grant_tokens_dto.dart';
import 'package:openapi/src/model/ai_admin_services_binding_configs_dtos_binding_config_dto.dart';
import 'package:openapi/src/model/ai_admin_services_binding_configs_dtos_binding_config_kind_meta_dto.dart';
import 'package:openapi/src/model/ai_admin_services_binding_configs_dtos_binding_config_upsert_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_application_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_board_info_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_bootstrap_status_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_manual_add_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_provisioning_credential_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_provisioning_issue_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_report_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_tools_call_req_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_un_bind_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_device_update_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_iot_device_dto.dart';
import 'package:openapi/src/model/ai_admin_services_device_dtos_user_show_device_list_vo.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_batch_id_req_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_doc_agg_vo_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_hit_vo_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_knowledge_base_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_knowledge_files_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_knowledge_text_import_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_list_vo_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_result_vo_dto.dart';
import 'package:openapi/src/model/ai_admin_services_knowledge_dtos_test_req_dto.dart';
import 'package:openapi/src/model/ai_admin_services_mcp_tools_dtos_mcp_tool_dto.dart';
import 'package:openapi/src/model/ai_admin_services_mcp_tools_dtos_mcp_tool_option_dto.dart';
import 'package:openapi/src/model/ai_admin_services_mcp_tools_dtos_mcp_tool_upsert_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_library_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_record_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_record_upsert_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_retrieval_config_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_rule_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_rule_upsert_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_runtime_context_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_search_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_search_hit_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_search_result_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_memory_write_config_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_runtime_signal_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_dtos_runtime_signal_status_update_dto.dart';
import 'package:openapi/src/model/ai_admin_services_memory_memory_rule_type.dart';
import 'package:openapi/src/model/ai_admin_services_rbac_dtos_menu_tree_dto.dart';
import 'package:openapi/src/model/ai_admin_services_rbac_dtos_role_create_dto.dart';
import 'package:openapi/src/model/ai_admin_services_rbac_dtos_role_dto.dart';
import 'package:openapi/src/model/ai_admin_services_rbac_dtos_role_menu_assign_dto.dart';
import 'package:openapi/src/model/ai_admin_services_rbac_dtos_role_update_dto.dart';
import 'package:openapi/src/model/ai_admin_services_rbac_dtos_user_info_dto.dart';
import 'package:openapi/src/model/ai_admin_services_rbac_dtos_user_role_assign_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_conversation_runtime_trace_snapshot_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_conversation_stage_aggregate_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_conversation_turn_trace_summary_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_asr_recognition_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_asr_recognition_response_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_conversation_asr_execution_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_conversation_execution_binding_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_conversation_llm_execution_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_conversation_tts_execution_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_llm_chat_message_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_llm_chat_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_llm_chat_response_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_llm_chat_usage_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_stage_execution_binding_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_stage_execution_trace_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_tts_synthesis_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_execution_dtos_tts_synthesis_response_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_orchestration_dtos_conversation_orchestration_plan_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_orchestration_dtos_conversation_orchestration_request_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_orchestration_dtos_model_invocation_profile_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_runtime_readiness_check_dto.dart';
import 'package:openapi/src/model/ai_admin_services_runtime_runtime_readiness_snapshot_dto.dart';
import 'package:openapi/src/model/ai_admin_services_voice_dtos_ota_entity_dto.dart';
import 'package:openapi/src/model/ai_admin_services_voice_dtos_timbre_data_dto.dart';
import 'package:openapi/src/model/ai_admin_services_voice_dtos_timbre_details_vo.dart';
import 'package:openapi/src/model/ai_admin_services_voice_dtos_tts_profile_option_dto.dart';
import 'package:openapi/src/model/ai_admin_services_voice_dtos_tts_voice_sync_result_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_auth_configuration_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_configuration_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_feature_configuration_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_global_feature_configuration_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_localization_configuration_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_localization_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_localization_resource_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_application_setting_configuration_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_clock_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_current_culture_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_current_user_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_date_time_format_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_iana_time_zone.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_entity_extension_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_enum_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_enum_field_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_api_create_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_api_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_api_get_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_api_update_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_attribute_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_feature_policy_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_global_feature_policy_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_permission_policy_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_policy_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_ui_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_ui_form_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_ui_lookup_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_extension_property_ui_table_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_localizable_string_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_module_extension_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_object_extending_object_extensions_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_time_zone.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_timing_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_application_configurations_windows_time_zone.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_multi_tenancy_current_tenant_dto.dart';
import 'package:openapi/src/model/volo_abp_asp_net_core_mvc_multi_tenancy_multi_tenancy_info_dto.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_action_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_application_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_controller_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_controller_interface_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_interface_method_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_method_parameter_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_module_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_parameter_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_property_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_return_value_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_modeling_type_api_description_model.dart';
import 'package:openapi/src/model/volo_abp_http_remote_service_error_info.dart';
import 'package:openapi/src/model/volo_abp_http_remote_service_error_response.dart';
import 'package:openapi/src/model/volo_abp_http_remote_service_validation_error_info.dart';
import 'package:openapi/src/model/volo_abp_localization_language_info.dart';
import 'package:openapi/src/model/volo_abp_name_value.dart';

part 'serializers.g.dart';

@SerializersFor([
  AiAdminControllersAgentRoleRuntimeTestFinalizeRequestDto,
  AiAdminControllersCreateTodoDto,
  AiAdminControllersDeviceStatusRequest,
  AiAdminControllersRuntimeServiceStatusDto,
  AiAdminControllersRuntimeStatusDto,
  AiAdminEntitiesProviderType,
  AiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo,
  AiAdminInfrastructurePageDataAiAdminServicesAdminDtosAuditLogPageItemVo,
  AiAdminInfrastructurePageDataAiAdminServicesAgentRolesDtosAgentRoleDto,
  AiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingOrderItemDto,
  AiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingSubscriptionItemDto,
  AiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingUsageItemDto,
  AiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto,
  AiAdminInfrastructurePageDataAiAdminServicesBindingConfigsDtosBindingConfigDto,
  AiAdminInfrastructurePageDataAiAdminServicesDeviceDtosUserShowDeviceListVo,
  AiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeBaseDto,
  AiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeFilesDto,
  AiAdminInfrastructurePageDataAiAdminServicesMcpToolsDtosMcpToolDto,
  AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto,
  AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto,
  AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosRuntimeSignalDto,
  AiAdminInfrastructurePageDataAiAdminServicesRbacDtosRoleDto,
  AiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto,
  AiAdminInfrastructurePageDataAiAdminServicesVoiceDtosTimbreDetailsVo,
  AiAdminInfrastructurePageDataSystemObject,
  AiAdminInfrastructureResultAiAdminControllersRuntimeStatusDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesAdminDtosAuditLogPageItemVo,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesAgentRolesDtosAgentRoleDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingOrderItemDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingSubscriptionItemDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingUsageItemDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBindingConfigsDtosBindingConfigDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesDeviceDtosUserShowDeviceListVo,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeBaseDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeFilesDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMcpToolsDtosMcpToolDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryLibraryDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosRuntimeSignalDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesRbacDtosRoleDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesVoiceDtosTimbreDetailsVo,
  AiAdminInfrastructureResultAiAdminInfrastructurePageDataSystemObject,
  AiAdminInfrastructureResultAiAdminServicesAdminDtosAdminSystemSettingsDto,
  AiAdminInfrastructureResultAiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto,
  AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosActionRuleDto,
  AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosAgentRoleBindingOptionsDto,
  AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosAgentRoleDto,
  AiAdminInfrastructureResultAiAdminServicesAgentRolesDtosAgentRoleReleaseDto,
  AiAdminInfrastructureResultAiAdminServicesAuthDtosPubConfigDto,
  AiAdminInfrastructureResultAiAdminServicesAuthDtosTokenDto,
  AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderDetailDto,
  AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderPayResultDto,
  AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingSummaryDto,
  AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingUsageReportResultDto,
  AiAdminInfrastructureResultAiAdminServicesBindingConfigsDtosBindingConfigDto,
  AiAdminInfrastructureResultAiAdminServicesDeviceDtosDeviceBootstrapStatusDto,
  AiAdminInfrastructureResultAiAdminServicesDeviceDtosDeviceProvisioningCredentialDto,
  AiAdminInfrastructureResultAiAdminServicesDeviceDtosIotDeviceDto,
  AiAdminInfrastructureResultAiAdminServicesKnowledgeDtosKnowledgeBaseDto,
  AiAdminInfrastructureResultAiAdminServicesKnowledgeDtosKnowledgeFilesDto,
  AiAdminInfrastructureResultAiAdminServicesKnowledgeDtosListVoDto,
  AiAdminInfrastructureResultAiAdminServicesKnowledgeDtosResultVoDto,
  AiAdminInfrastructureResultAiAdminServicesMcpToolsDtosMcpToolDto,
  AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto,
  AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRecordDto,
  AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto,
  AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemorySearchResultDto,
  AiAdminInfrastructureResultAiAdminServicesMemoryDtosRuntimeSignalDto,
  AiAdminInfrastructureResultAiAdminServicesRbacDtosUserInfoDto,
  AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosAsrRecognitionResponseDto,
  AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosConversationExecutionBindingDto,
  AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosLlmChatResponseDto,
  AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto,
  AiAdminInfrastructureResultAiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationPlanDto,
  AiAdminInfrastructureResultAiAdminServicesVoiceDtosOtaEntityDto,
  AiAdminInfrastructureResultAiAdminServicesVoiceDtosTimbreDetailsVo,
  AiAdminInfrastructureResultAiAdminServicesVoiceDtosTtsVoiceSyncResultDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosAgentRoleDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosAgentRoleReleaseDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosOptionItemDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesBillingDtosBillingPlanItemDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesBindingConfigsDtosBindingConfigKindMetaDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesDeviceDtosIotDeviceDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMcpToolsDtosMcpToolOptionDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesMemoryDtosMemoryRuleDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosMenuTreeDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosRoleDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesVoiceDtosTtsProfileOptionDto,
  AiAdminInfrastructureResultSystemCollectionsGenericListSystemInt64,
  AiAdminInfrastructureResultSystemCollectionsGenericListSystemObject,
  AiAdminInfrastructureResultSystemCollectionsGenericListSystemString,
  AiAdminInfrastructureResultSystemObject,
  AiAdminInfrastructureResultSystemString,
  AiAdminServicesAdminDtosAdminPageUserVo,
  AiAdminServicesAdminDtosAdminSystemBillingSettingsDto,
  AiAdminServicesAdminDtosAdminSystemLogSettingsDto,
  AiAdminServicesAdminDtosAdminSystemRuntimeSettingsDto,
  AiAdminServicesAdminDtosAdminSystemServerSettingsDto,
  AiAdminServicesAdminDtosAdminSystemSettingsDto,
  AiAdminServicesAdminDtosAuditEntityChangeVo,
  AiAdminServicesAdminDtosAuditLogActionVo,
  AiAdminServicesAdminDtosAuditLogPageItemVo,
  AiAdminServicesAdminDtosAuditPropertyChangeVo,
  AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeDto,
  AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeHitDto,
  AiAdminServicesAgentRolesAgentRoleRuntimeTestRequestDto,
  AiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto,
  AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto,
  AiAdminServicesAgentRolesDtosActionRuleDto,
  AiAdminServicesAgentRolesDtosActionRuleUpsertDto,
  AiAdminServicesAgentRolesDtosAgentRoleBindingOptionsDto,
  AiAdminServicesAgentRolesDtosAgentRoleContextProviderDto,
  AiAdminServicesAgentRolesDtosAgentRoleDto,
  AiAdminServicesAgentRolesDtosAgentRoleKnowledgeBindingDto,
  AiAdminServicesAgentRolesDtosAgentRolePluginMappingDto,
  AiAdminServicesAgentRolesDtosAgentRolePublishDto,
  AiAdminServicesAgentRolesDtosAgentRoleReleaseDto,
  AiAdminServicesAgentRolesDtosAgentRoleUpsertDto,
  AiAdminServicesAgentRolesDtosOptionItemDto,
  AiAdminServicesAuthDtosLoginDto,
  AiAdminServicesAuthDtosMenuItemDto,
  AiAdminServicesAuthDtosPasswordDto,
  AiAdminServicesAuthDtosPubConfigDto,
  AiAdminServicesAuthDtosRegisterDto,
  AiAdminServicesAuthDtosRetrievePasswordDto,
  AiAdminServicesAuthDtosSmsVerificationDto,
  AiAdminServicesAuthDtosTokenDto,
  AiAdminServicesBillingDtosAdminBillingOrderItemDto,
  AiAdminServicesBillingDtosAdminBillingSubscriptionItemDto,
  AiAdminServicesBillingDtosAdminBillingUsageItemDto,
  AiAdminServicesBillingDtosAdminMarkOrderPaidDto,
  AiAdminServicesBillingDtosBillingOrderDetailDto,
  AiAdminServicesBillingDtosBillingOrderItemDto,
  AiAdminServicesBillingDtosBillingOrderPayDto,
  AiAdminServicesBillingDtosBillingOrderPayResultDto,
  AiAdminServicesBillingDtosBillingPlanItemDto,
  AiAdminServicesBillingDtosBillingSummaryDto,
  AiAdminServicesBillingDtosBillingUsageReportDto,
  AiAdminServicesBillingDtosBillingUsageReportResultDto,
  AiAdminServicesBillingDtosCreateBillingOrderDto,
  AiAdminServicesBillingDtosManualGrantTokensDto,
  AiAdminServicesBindingConfigsDtosBindingConfigDto,
  AiAdminServicesBindingConfigsDtosBindingConfigKindMetaDto,
  AiAdminServicesBindingConfigsDtosBindingConfigUpsertDto,
  AiAdminServicesDeviceDtosDeviceApplicationDto,
  AiAdminServicesDeviceDtosDeviceBoardInfoDto,
  AiAdminServicesDeviceDtosDeviceBootstrapStatusDto,
  AiAdminServicesDeviceDtosDeviceManualAddDto,
  AiAdminServicesDeviceDtosDeviceProvisioningCredentialDto,
  AiAdminServicesDeviceDtosDeviceProvisioningIssueDto,
  AiAdminServicesDeviceDtosDeviceReportDto,
  AiAdminServicesDeviceDtosDeviceToolsCallReqDto,
  AiAdminServicesDeviceDtosDeviceUnBindDto,
  AiAdminServicesDeviceDtosDeviceUpdateDto,
  AiAdminServicesDeviceDtosIotDeviceDto,
  AiAdminServicesDeviceDtosUserShowDeviceListVo,
  AiAdminServicesKnowledgeDtosBatchIdReqDto,
  AiAdminServicesKnowledgeDtosDocAggVoDto,
  AiAdminServicesKnowledgeDtosHitVoDto,
  AiAdminServicesKnowledgeDtosKnowledgeBaseDto,
  AiAdminServicesKnowledgeDtosKnowledgeFilesDto,
  AiAdminServicesKnowledgeDtosKnowledgeTextImportDto,
  AiAdminServicesKnowledgeDtosListVoDto,
  AiAdminServicesKnowledgeDtosResultVoDto,
  AiAdminServicesKnowledgeDtosTestReqDto,
  AiAdminServicesMcpToolsDtosMcpToolDto,
  AiAdminServicesMcpToolsDtosMcpToolOptionDto,
  AiAdminServicesMcpToolsDtosMcpToolUpsertDto,
  AiAdminServicesMemoryDtosMemoryLibraryDto,
  AiAdminServicesMemoryDtosMemoryRecordDto,
  AiAdminServicesMemoryDtosMemoryRecordUpsertDto,
  AiAdminServicesMemoryDtosMemoryRetrievalConfigDto,
  AiAdminServicesMemoryDtosMemoryRuleDto,
  AiAdminServicesMemoryDtosMemoryRuleUpsertDto,
  AiAdminServicesMemoryDtosMemoryRuntimeContextDto,
  AiAdminServicesMemoryDtosMemorySearchDto,
  AiAdminServicesMemoryDtosMemorySearchHitDto,
  AiAdminServicesMemoryDtosMemorySearchResultDto,
  AiAdminServicesMemoryDtosMemoryWriteConfigDto,
  AiAdminServicesMemoryDtosRuntimeSignalDto,
  AiAdminServicesMemoryDtosRuntimeSignalStatusUpdateDto,
  AiAdminServicesMemoryMemoryRuleType,
  AiAdminServicesRbacDtosMenuTreeDto,
  AiAdminServicesRbacDtosRoleCreateDto,
  AiAdminServicesRbacDtosRoleDto,
  AiAdminServicesRbacDtosRoleMenuAssignDto,
  AiAdminServicesRbacDtosRoleUpdateDto,
  AiAdminServicesRbacDtosUserInfoDto,
  AiAdminServicesRbacDtosUserRoleAssignDto,
  AiAdminServicesRuntimeConversationRuntimeTraceSnapshotDto,
  AiAdminServicesRuntimeConversationStageAggregateDto,
  AiAdminServicesRuntimeConversationTurnTraceSummaryDto,
  AiAdminServicesRuntimeExecutionDtosAsrRecognitionRequestDto,
  AiAdminServicesRuntimeExecutionDtosAsrRecognitionResponseDto,
  AiAdminServicesRuntimeExecutionDtosConversationAsrExecutionRequestDto,
  AiAdminServicesRuntimeExecutionDtosConversationExecutionBindingDto,
  AiAdminServicesRuntimeExecutionDtosConversationLlmExecutionRequestDto,
  AiAdminServicesRuntimeExecutionDtosConversationTtsExecutionRequestDto,
  AiAdminServicesRuntimeExecutionDtosLlmChatMessageDto,
  AiAdminServicesRuntimeExecutionDtosLlmChatRequestDto,
  AiAdminServicesRuntimeExecutionDtosLlmChatResponseDto,
  AiAdminServicesRuntimeExecutionDtosLlmChatUsageDto,
  AiAdminServicesRuntimeExecutionDtosStageExecutionBindingDto,
  AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto,
  AiAdminServicesRuntimeExecutionDtosTtsSynthesisRequestDto,
  AiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto,
  AiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationPlanDto,
  AiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto,
  AiAdminServicesRuntimeOrchestrationDtosModelInvocationProfileDto,
  AiAdminServicesRuntimeRuntimeReadinessCheckDto,
  AiAdminServicesRuntimeRuntimeReadinessSnapshotDto,
  AiAdminServicesVoiceDtosOtaEntityDto,
  AiAdminServicesVoiceDtosTimbreDataDto,
  AiAdminServicesVoiceDtosTimbreDetailsVo,
  AiAdminServicesVoiceDtosTtsProfileOptionDto,
  AiAdminServicesVoiceDtosTtsVoiceSyncResultDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationConfigurationDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationGlobalFeatureConfigurationDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumFieldDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiCreateDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiGetDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiUpdateDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyAttributeDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyFeaturePolicyDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyGlobalFeaturePolicyDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyPermissionPolicyDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyPolicyDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiFormDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiLookupDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiTableDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingLocalizableStringDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone,
  VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto,
  VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone,
  VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto,
  VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto,
  VoloAbpHttpModelingActionApiDescriptionModel,
  VoloAbpHttpModelingApplicationApiDescriptionModel,
  VoloAbpHttpModelingControllerApiDescriptionModel,
  VoloAbpHttpModelingControllerInterfaceApiDescriptionModel,
  VoloAbpHttpModelingInterfaceMethodApiDescriptionModel,
  VoloAbpHttpModelingMethodParameterApiDescriptionModel,
  VoloAbpHttpModelingModuleApiDescriptionModel,
  VoloAbpHttpModelingParameterApiDescriptionModel,
  VoloAbpHttpModelingPropertyApiDescriptionModel,
  VoloAbpHttpModelingReturnValueApiDescriptionModel,
  VoloAbpHttpModelingTypeApiDescriptionModel,
  VoloAbpHttpRemoteServiceErrorInfo,
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpHttpRemoteServiceValidationErrorInfo,
  VoloAbpLocalizationLanguageInfo,
  VoloAbpNameValue,
])
Serializers serializers = (_$serializers.toBuilder()
      ..addBuilderFactory(
        const FullType(BuiltMap, [FullType(String), FullType(String)]),
        () => MapBuilder<String, String>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltMap, [FullType(String), FullType(BuiltList, [FullType(String)])]),
        () => MapBuilder<String, BuiltList<String>>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(String)]),
        () => ListBuilder<String>(),
      )
      ..add(const OneOfSerializer())
      ..add(const AnyOfSerializer())
      ..add(const DateSerializer())
      ..add(Iso8601DateTimeSerializer())
    ).build();

Serializers standardSerializers =
    (serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();
