/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAdminDtosAuditLogActionVo } from './aiAdminServicesAdminDtosAuditLogActionVo.model';
import { AiAdminServicesAdminDtosAuditEntityChangeVo } from './aiAdminServicesAdminDtosAuditEntityChangeVo.model';


export interface AiAdminServicesAdminDtosAuditLogPageItemVo { 
    id?: string | null;
    applicationName?: string | null;
    operatorId?: string | null;
    userName?: string | null;
    clientIpAddress?: string | null;
    browserInfo?: string | null;
    correlationId?: string | null;
    httpMethod?: string | null;
    httpStatusCode?: number | null;
    url?: string | null;
    executionTime?: string;
    executionDuration?: number;
    hasException?: boolean;
    exceptions?: string | null;
    comments?: string | null;
    actionCount?: number;
    entityChangeCount?: number;
    actions?: Array<AiAdminServicesAdminDtosAuditLogActionVo> | null;
    entityChanges?: Array<AiAdminServicesAdminDtosAuditEntityChangeVo> | null;
}

