/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesMemoryDtosMemoryRuleDto } from './aiAdminServicesMemoryDtosMemoryRuleDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryRuleDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesMemoryDtosMemoryRuleDto;
}

