/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminControllersRuntimeServiceStatusDto } from './aiAdminControllersRuntimeServiceStatusDto.model';
import { AiAdminServicesRuntimeRuntimeReadinessSnapshotDto } from './aiAdminServicesRuntimeRuntimeReadinessSnapshotDto.model';
import { AiAdminServicesRuntimeConversationRuntimeTraceSnapshotDto } from './aiAdminServicesRuntimeConversationRuntimeTraceSnapshotDto.model';


export interface AiAdminControllersRuntimeStatusDto { 
    nodeId?: string | null;
    runtimeEnabled?: boolean;
    nodeStartedAtUtc?: string;
    onlineDeviceCount?: number;
    activeConversationCount?: number;
    aliveConversationCount?: number;
    udpSessionCount?: number;
    localSpeechIdleTimeoutMs?: number;
    services?: Array<AiAdminControllersRuntimeServiceStatusDto> | null;
    conversationTrace?: AiAdminServicesRuntimeConversationRuntimeTraceSnapshotDto;
    readiness?: AiAdminServicesRuntimeRuntimeReadinessSnapshotDto;
}

