/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRuntimeRuntimeReadinessCheckDto } from './aiAdminServicesRuntimeRuntimeReadinessCheckDto.model';


export interface AiAdminServicesRuntimeRuntimeReadinessSnapshotDto { 
    ready?: boolean;
    severity?: string | null;
    passedCheckCount?: number;
    warningCheckCount?: number;
    failedCheckCount?: number;
    checks?: Array<AiAdminServicesRuntimeRuntimeReadinessCheckDto> | null;
}

