/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAgentRolesDtosAgentRoleReleaseDto { 
    id?: string | null;
    roleId?: string | null;
    version?: string | null;
    status?: string | null;
    snapshotJson?: string | null;
    remark?: string | null;
    publishedAt?: string | null;
    creator?: number | null;
    createdAt?: string | null;
    updater?: number | null;
    updatedAt?: string | null;
}

