/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAdminDtosAuditPropertyChangeVo } from './aiAdminServicesAdminDtosAuditPropertyChangeVo.model';


export interface AiAdminServicesAdminDtosAuditEntityChangeVo { 
    changeType?: string | null;
    entityTypeFullName?: string | null;
    entityId?: string | null;
    changeTime?: string;
    propertyChanges?: Array<AiAdminServicesAdminDtosAuditPropertyChangeVo> | null;
}

