/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAdminDtosAdminSystemBillingSettingsDto } from './aiAdminServicesAdminDtosAdminSystemBillingSettingsDto.model';
import { AiAdminServicesAdminDtosAdminSystemLogSettingsDto } from './aiAdminServicesAdminDtosAdminSystemLogSettingsDto.model';
import { AiAdminServicesAdminDtosAdminSystemServerSettingsDto } from './aiAdminServicesAdminDtosAdminSystemServerSettingsDto.model';
import { AiAdminServicesAdminDtosAdminSystemRuntimeSettingsDto } from './aiAdminServicesAdminDtosAdminSystemRuntimeSettingsDto.model';


export interface AiAdminServicesAdminDtosAdminSystemSettingsDto { 
    server?: AiAdminServicesAdminDtosAdminSystemServerSettingsDto;
    log?: AiAdminServicesAdminDtosAdminSystemLogSettingsDto;
    runtime?: AiAdminServicesAdminDtosAdminSystemRuntimeSettingsDto;
    billing?: AiAdminServicesAdminDtosAdminSystemBillingSettingsDto;
}

