/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAdminDtosAdminSystemRuntimeSettingsDto { 
    deleteAudio?: boolean;
    closeConnectionNoVoiceTime?: number;
    ttsTimeout?: number;
    enableWakeupWordsResponseCache?: boolean;
    enableGreeting?: boolean;
    enableStopTtsNotify?: boolean;
    stopTtsNotifyVoice?: string | null;
    exitCommands?: string | null;
    otto?: string | null;
    wakeupWords?: string | null;
    deviceMaxOutputSize?: number | null;
    voiceprintUrl?: string | null;
    voiceprintSimilarityThreshold?: number | null;
}

