/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAdminDtosAuditLogPageItemVo } from './aiAdminServicesAdminDtosAuditLogPageItemVo.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesAdminDtosAuditLogPageItemVo { 
    total?: number;
    list?: Array<AiAdminServicesAdminDtosAuditLogPageItemVo> | null;
}

