/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesBindingConfigsDtosBindingConfigDto } from './aiAdminServicesBindingConfigsDtosBindingConfigDto.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesBindingConfigsDtosBindingConfigDto { 
    total?: number;
    list?: Array<AiAdminServicesBindingConfigsDtosBindingConfigDto> | null;
}

