/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesVoiceDtosTtsVoiceSyncResultDto { 
    providerCode?: string | null;
    ttsProfileId?: string | null;
    remoteCount?: number;
    createdCount?: number;
    updatedCount?: number;
    skippedCount?: number;
    message?: string | null;
}

