/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesDeviceDtosIotDeviceDto } from './aiAdminServicesDeviceDtosIotDeviceDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesDeviceDtosIotDeviceDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesDeviceDtosIotDeviceDto;
}

