/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesBillingDtosBillingUsageReportResultDto { 
    recorded?: boolean;
    idempotencyKey?: string | null;
    normalizedTokens?: number;
    consumedTokens?: number;
    remainingTokens?: number;
    isLowBalance?: boolean;
    isExhausted?: boolean;
    chargeStatus?: string | null;
    periodKey?: string | null;
}

