/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesMemoryDtosMemoryRecordUpsertDto { 
    agentId?: string | null;
    deviceId?: string | null;
    userId?: number | null;
    entityId?: string | null;
    sessionId?: string | null;
    ruleId?: string | null;
    ruleCode?: string | null;
    entityScope?: string | null;
    recordType?: string | null;
    title?: string | null;
    content?: string | null;
    summary?: string | null;
    keywords?: any | null;
    payloadJson?: any | null;
    canonicalKey?: string | null;
    contentHash?: string | null;
    importance?: number | null;
    confidence?: number | null;
    isPinned?: number | null;
    source?: string | null;
    sourceChatHistoryId?: string | null;
    sourceTurnId?: string | null;
    sourceRunId?: string | null;
    expiresAt?: string | null;
}

