/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesDeviceDtosDeviceProvisioningIssueDto { 
    macAddress?: string | null;
    alias?: string | null;
    board?: string | null;
    appVersion?: string | null;
    agentRoleId?: string | null;
    agentRoleReleaseId?: string | null;
    rotateCredential?: boolean;
}

