/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesMcpToolsDtosMcpToolUpsertDto { 
    code: string;
    name: string;
    description?: string | null;
    category?: string | null;
    paramSchema?: string | null;
    status: string;
    sort?: number;
}

