/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesVoiceDtosTimbreDataDto { 
    languages?: string | null;
    name?: string | null;
    remark?: string | null;
    referenceAudio?: string | null;
    referenceText?: string | null;
    sort?: number | null;
    ttsProfileId?: string | null;
    ttsVoice?: string | null;
    voiceDemo?: string | null;
}

