/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesMcpToolsDtosMcpToolDto } from './aiAdminServicesMcpToolsDtosMcpToolDto.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesMcpToolsDtosMcpToolDto { 
    total?: number;
    list?: Array<AiAdminServicesMcpToolsDtosMcpToolDto> | null;
}

