/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto } from './aiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto.model';
import { AiAdminServicesRuntimeExecutionDtosLlmChatRequestDto } from './aiAdminServicesRuntimeExecutionDtosLlmChatRequestDto.model';


export interface AiAdminServicesRuntimeExecutionDtosConversationLlmExecutionRequestDto { 
    orchestration?: AiAdminServicesRuntimeOrchestrationDtosConversationOrchestrationRequestDto;
    request?: AiAdminServicesRuntimeExecutionDtosLlmChatRequestDto;
}

