/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAgentRolesAgentRoleRuntimeTestRequestDto { 
    agentRoleId?: string | null;
    agentRoleCode?: string | null;
    agentRoleReleaseId?: string | null;
    sessionId?: string | null;
    deviceId?: string | null;
    userText?: string | null;
    audioBase64?: string | null;
    audioFormat?: string | null;
    language?: string | null;
    responseFormat?: string | null;
}

