/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAuthDtosMenuItemDto } from './aiAdminServicesAuthDtosMenuItemDto.model';


export interface AiAdminServicesAuthDtosPubConfigDto { 
    menus?: Array<AiAdminServicesAuthDtosMenuItemDto> | null;
    allowUserRegister?: boolean;
    turnstileSiteKey?: string | null;
}

