/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesMemoryDtosMemoryRecordDto } from './aiAdminServicesMemoryDtosMemoryRecordDto.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto { 
    total?: number;
    list?: Array<AiAdminServicesMemoryDtosMemoryRecordDto> | null;
}

