/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesBillingDtosAdminMarkOrderPaidDto { 
    transactionNo?: string | null;
    paidAt?: string | null;
    remark?: string | null;
}

