/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesVoiceDtosOtaEntityDto } from './aiAdminServicesVoiceDtosOtaEntityDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesVoiceDtosOtaEntityDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesVoiceDtosOtaEntityDto;
}

