/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesKnowledgeDtosHitVoDto } from './aiAdminServicesKnowledgeDtosHitVoDto.model';
import { AiAdminServicesKnowledgeDtosDocAggVoDto } from './aiAdminServicesKnowledgeDtosDocAggVoDto.model';


export interface AiAdminServicesKnowledgeDtosResultVoDto { 
    chunks?: Array<AiAdminServicesKnowledgeDtosHitVoDto> | null;
    total?: number | null;
    docAggs?: Array<AiAdminServicesKnowledgeDtosDocAggVoDto> | null;
    query?: string | null;
    effectiveQuery?: string | null;
    topK?: number | null;
    threshold?: number | null;
    rewriteApplied?: boolean | null;
}

