/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesVoiceDtosOtaEntityDto } from './aiAdminServicesVoiceDtosOtaEntityDto.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto { 
    total?: number;
    list?: Array<AiAdminServicesVoiceDtosOtaEntityDto> | null;
}

