/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesVoiceDtosTimbreDetailsVo } from './aiAdminServicesVoiceDtosTimbreDetailsVo.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesVoiceDtosTimbreDetailsVo { 
    total?: number;
    list?: Array<AiAdminServicesVoiceDtosTimbreDetailsVo> | null;
}

