/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesBillingDtosAdminBillingOrderItemDto { 
    id?: string | null;
    orderNo?: string | null;
    planId?: string | null;
    planCode?: string | null;
    planName?: string | null;
    orderType?: string | null;
    providerCode?: string | null;
    currencyCode?: string | null;
    amount?: number;
    grantedTokens?: number;
    status?: string | null;
    externalTradeNo?: string | null;
    paidAt?: string | null;
    activatedAt?: string | null;
    createDate?: string | null;
    userId?: number;
    username?: string | null;
    mobile?: string | null;
}

