/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto } from './aiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto.model';


export interface AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminInfrastructurePageDataAiAdminServicesVoiceDtosOtaEntityDto;
}

