/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminControllersCreateTodoDto { 
    title?: string | null;
    content?: string | null;
    scheduledAt?: string | null;
    userId?: number | null;
    deviceId?: string | null;
    agentRoleId?: string | null;
}

