/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesDeviceDtosUserShowDeviceListVo } from './aiAdminServicesDeviceDtosUserShowDeviceListVo.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesDeviceDtosUserShowDeviceListVo { 
    total?: number;
    list?: Array<AiAdminServicesDeviceDtosUserShowDeviceListVo> | null;
}

