/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAdminDtosAdminPageUserVo { 
    userid?: string | null;
    mobile?: string | null;
    status?: number | null;
    createDate?: string | null;
    deviceCount?: string | null;
}

