/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesMemoryDtosRuntimeSignalStatusUpdateDto { 
    status?: string | null;
    errorMessage?: string | null;
    scheduledAt?: string | null;
}

