/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesBillingDtosBillingUsageReportResultDto } from './aiAdminServicesBillingDtosBillingUsageReportResultDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingUsageReportResultDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesBillingDtosBillingUsageReportResultDto;
}

