/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesMemoryDtosRuntimeSignalDto } from './aiAdminServicesMemoryDtosRuntimeSignalDto.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosRuntimeSignalDto { 
    total?: number;
    list?: Array<AiAdminServicesMemoryDtosRuntimeSignalDto> | null;
}

