/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesKnowledgeDtosResultVoDto } from './aiAdminServicesKnowledgeDtosResultVoDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesKnowledgeDtosResultVoDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesKnowledgeDtosResultVoDto;
}

