/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesDeviceDtosIotDeviceDto { 
    id?: string | null;
    macAddress?: string | null;
    alias?: string | null;
    agentRoleId?: string | null;
    agentRoleName?: string | null;
    agentRoleReleaseId?: string | null;
    agentRoleVersion?: string | null;
    board?: string | null;
    appVersion?: string | null;
    isOnline?: boolean;
    lastConnectedAt?: string | null;
    autoUpdate?: number;
}

