/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesKnowledgeDtosTestReqDto { 
    question?: string | null;
    query?: string | null;
    rewriteQuery?: string | null;
    topK?: number | null;
    threshold?: number | null;
    page?: number | null;
    highlight?: boolean | null;
}

