/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRbacDtosMenuTreeDto } from './aiAdminServicesRbacDtosMenuTreeDto.model';


export interface AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosMenuTreeDto { 
    code?: number;
    msg?: string | null;
    data?: Array<AiAdminServicesRbacDtosMenuTreeDto> | null;
}

