/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto } from './aiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto;
}

