/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesKnowledgeDtosKnowledgeBaseDto { 
    id?: string | null;
    datasetId?: string | null;
    name?: string | null;
    avatar?: string | null;
    description?: string | null;
    permission?: string | null;
    chunkMethod?: string | null;
    parserConfig?: string | null;
    chunkCount?: number | null;
    tokenNum?: number | null;
    status?: number | null;
    creator?: number | null;
    createdAt?: string | null;
    updater?: number | null;
    updatedAt?: string | null;
    documentCount?: number | null;
}

