/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesMemoryDtosMemorySearchHitDto } from './aiAdminServicesMemoryDtosMemorySearchHitDto.model';


export interface AiAdminServicesMemoryDtosMemoryRuntimeContextDto { 
    libraryId?: string | null;
    libraryName?: string | null;
    entityScope?: string | null;
    entityId?: string | null;
    topK?: number;
    minScore?: number | null;
    intentRecall?: boolean;
    queryRewrite?: boolean;
    rerank?: boolean;
    records?: Array<AiAdminServicesMemoryDtosMemorySearchHitDto> | null;
}

