/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo } from './aiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo.model';


export interface AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo { 
    code?: number;
    msg?: string | null;
    data?: AiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo;
}

