/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminControllersRuntimeServiceStatusDto { 
    key?: string | null;
    name?: string | null;
    protocol?: string | null;
    statusText?: string | null;
    severity?: string | null;
    endpoint?: string | null;
    description?: string | null;
}

