/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminEntitiesProviderType } from './aiAdminEntitiesProviderType.model';


export interface AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto { 
    sessionId?: string | null;
    deviceId?: string | null;
    agentRoleId?: string | null;
    agentRoleCode?: string | null;
    agentRoleVersion?: string | null;
    agentRoleReleaseId?: string | null;
    agentRoleConfigSource?: string | null;
    stage?: string | null;
    requestedInvocationMode?: string | null;
    plannedInvocationMode?: string | null;
    actualInvocationMode?: string | null;
    fallbackMode?: string | null;
    fallbackReason?: string | null;
    failureReason?: string | null;
    profileId?: string | null;
    providerCode?: string | null;
    providerType?: AiAdminEntitiesProviderType;
    providerName?: string | null;
    providerFamily?: string | null;
    capabilitySource?: string | null;
    capabilityTags?: Array<string> | null;
    succeeded?: boolean;
    durationMs?: number;
    errorCode?: string | null;
    errorMessage?: string | null;
}



