/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesBillingDtosAdminBillingSubscriptionItemDto { 
    userId?: number;
    username?: string | null;
    mobile?: string | null;
    planCode?: string | null;
    planName?: string | null;
    subscriptionStatus?: string | null;
    periodKey?: string | null;
    totalTokens?: number;
    consumedTokens?: number;
    remainingTokens?: number;
    periodEndAt?: string | null;
    isLowBalance?: boolean;
    isExhausted?: boolean;
}

