/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesBillingDtosBillingOrderItemDto } from './aiAdminServicesBillingDtosBillingOrderItemDto.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto { 
    total?: number;
    list?: Array<AiAdminServicesBillingDtosBillingOrderItemDto> | null;
}

