/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesRuntimeExecutionDtosTtsSynthesisRequestDto { 
    text?: string | null;
    voice?: string | null;
    responseFormat?: string | null;
    speed?: number | null;
    extraOptions?: { [key: string]: any | null; } | null;
}

