/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesKnowledgeDtosDocAggVoDto { 
    count?: number | null;
    docName?: string | null;
    docId?: string | null;
}

