/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto } from './aiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto.model';


export interface AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto { 
    status?: string | null;
    durationMs?: number;
    errorMessage?: string | null;
    trace?: AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto;
}

