/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAuthDtosLoginDto { 
    username?: string | null;
    password?: string | null;
    mobileCaptcha?: string | null;
    captchaId?: string | null;
    turnstileToken?: string | null;
}

