/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesKnowledgeDtosKnowledgeFilesDto } from './aiAdminServicesKnowledgeDtosKnowledgeFilesDto.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeFilesDto { 
    total?: number;
    list?: Array<AiAdminServicesKnowledgeDtosKnowledgeFilesDto> | null;
}

