/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum AiAdminServicesMemoryMemoryRuleType {

    profile = 'profile',

    node = 'node',

    risk = 'risk',

    health_followup = 'health_followup',

    todo = 'todo',

    reminder = 'reminder'
}

