/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAgentRolesDtosActionRuleDto { 
    id?: string | null;
    agentRoleId?: string | null;
    actionType?: string | null;
    name?: string | null;
    instruction?: string | null;
    isEnabled?: number;
    creator?: number | null;
    createdAt?: string | null;
    updater?: number | null;
    updatedAt?: string | null;
}

