/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingSubscriptionItemDto } from './aiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingSubscriptionItemDto.model';


export interface AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingSubscriptionItemDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminInfrastructurePageDataAiAdminServicesBillingDtosAdminBillingSubscriptionItemDto;
}

