/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesBillingDtosBillingUsageReportDto { 
    macAddress?: string | null;
    sessionId?: string | null;
    serviceType?: string | null;
    providerCode?: string | null;
    modelConfigId?: string | null;
    unitType?: string | null;
    rawUnits?: number;
    normalizedTokens?: number | null;
    rawUsageJson?: string | null;
    idempotencyKey?: string | null;
    reportTime?: number | null;
}

