/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesBillingDtosAdminBillingUsageItemDto { 
    id?: string | null;
    userId?: number;
    username?: string | null;
    mobile?: string | null;
    agentId?: string | null;
    deviceId?: string | null;
    sessionId?: string | null;
    serviceType?: string | null;
    providerCode?: string | null;
    unitType?: string | null;
    rawUnits?: number;
    normalizedTokens?: number;
    chargeStatus?: string | null;
    happenedAt?: string | null;
}

