/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeHitDto } from './aiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeHitDto.model';


export interface AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeDto { 
    hasBindings?: boolean;
    hasHits?: boolean;
    fallbackReplyText?: string | null;
    injectedSystemPrompt?: string | null;
    hits?: Array<AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeHitDto> | null;
}

