/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRuntimeExecutionDtosLlmChatUsageDto } from './aiAdminServicesRuntimeExecutionDtosLlmChatUsageDto.model';
import { AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto } from './aiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto.model';


export interface AiAdminServicesRuntimeExecutionDtosLlmChatResponseDto { 
    invocationMode?: string | null;
    providerResponseId?: string | null;
    model?: string | null;
    text?: string | null;
    finishReason?: string | null;
    usage?: AiAdminServicesRuntimeExecutionDtosLlmChatUsageDto;
    rawResponseJson?: string | null;
    stageTrace?: AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto;
}

