/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesBillingDtosBillingOrderPayResultDto } from './aiAdminServicesBillingDtosBillingOrderPayResultDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesBillingDtosBillingOrderPayResultDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesBillingDtosBillingOrderPayResultDto;
}

