/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesBillingDtosBillingPlanItemDto } from './aiAdminServicesBillingDtosBillingPlanItemDto.model';


export interface AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesBillingDtosBillingPlanItemDto { 
    code?: number;
    msg?: string | null;
    data?: Array<AiAdminServicesBillingDtosBillingPlanItemDto> | null;
}

