/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesMcpToolsDtosMcpToolDto { 
    id?: string | null;
    code?: string | null;
    name?: string | null;
    description?: string | null;
    category?: string | null;
    isSystem?: boolean;
    paramSchema?: string | null;
    status?: string | null;
    sort?: number;
    createdAt?: string;
    updatedAt?: string | null;
}

