/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeHitDto { 
    datasetId?: string | null;
    documentId?: string | null;
    documentName?: string | null;
    content?: string | null;
    score?: number;
}

