/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesMemoryDtosMemoryLibraryDto } from './aiAdminServicesMemoryDtosMemoryLibraryDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesMemoryDtosMemoryLibraryDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesMemoryDtosMemoryLibraryDto;
}

