/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto } from './aiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto.model';


export interface AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosMemoryRecordDto;
}

