/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAgentRolesDtosAgentRoleReleaseDto } from './aiAdminServicesAgentRolesDtosAgentRoleReleaseDto.model';


export interface AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosAgentRoleReleaseDto { 
    code?: number;
    msg?: string | null;
    data?: Array<AiAdminServicesAgentRolesDtosAgentRoleReleaseDto> | null;
}

