/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto } from './aiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto.model';
import { AiAdminServicesMemoryDtosMemoryRuntimeContextDto } from './aiAdminServicesMemoryDtosMemoryRuntimeContextDto.model';
import { AiAdminServicesRuntimeExecutionDtosAsrRecognitionResponseDto } from './aiAdminServicesRuntimeExecutionDtosAsrRecognitionResponseDto.model';
import { AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeDto } from './aiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeDto.model';
import { AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto } from './aiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto.model';
import { AiAdminServicesRuntimeExecutionDtosLlmChatResponseDto } from './aiAdminServicesRuntimeExecutionDtosLlmChatResponseDto.model';
import { AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto } from './aiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto.model';


export interface AiAdminServicesAgentRolesAgentRoleRuntimeTestResultDto { 
    sessionId?: string | null;
    inputMode?: string | null;
    agentRoleId?: string | null;
    agentRoleCode?: string | null;
    agentRoleName?: string | null;
    agentRoleReleaseId?: string | null;
    agentRoleVersion?: string | null;
    runtimeConfigSource?: string | null;
    deviceId?: string | null;
    transcript?: string | null;
    replyText?: string | null;
    asrStage?: AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto;
    memoryRetrievalStage?: AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto;
    knowledgeRetrievalStage?: AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto;
    llmStage?: AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto;
    ttsStage?: AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto;
    memoryExtractionStage?: AiAdminServicesAgentRolesAgentRoleRuntimeTestStageDto;
    asr?: AiAdminServicesRuntimeExecutionDtosAsrRecognitionResponseDto;
    knowledge?: AiAdminServicesAgentRolesAgentRoleRuntimeTestKnowledgeDto;
    memoryBefore?: AiAdminServicesMemoryDtosMemoryRuntimeContextDto;
    llm?: AiAdminServicesRuntimeExecutionDtosLlmChatResponseDto;
    tts?: AiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto;
    memoryChangedCount?: number;
    memoryAfter?: AiAdminServicesMemoryDtosMemoryRuntimeContextDto;
    stageTraces?: Array<AiAdminServicesRuntimeExecutionDtosStageExecutionTraceDto> | null;
    warnings?: Array<string> | null;
}

