/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesKnowledgeDtosKnowledgeFilesDto { 
    id?: string | null;
    documentId?: string | null;
    datasetId?: string | null;
    name?: string | null;
    fileType?: string | null;
    fileSize?: number | null;
    filePath?: string | null;
    progress?: number | null;
    sourceType?: string | null;
    chunkMethod?: string | null;
    parserConfig?: any | null;
    status?: string | null;
    run?: string | null;
    creator?: number | null;
    createdAt?: string | null;
    updater?: number | null;
    updatedAt?: string | null;
    chunkCount?: number | null;
    tokenCount?: number | null;
    error?: string | null;
}

