/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAdminDtosAdminSystemSettingsDto } from './aiAdminServicesAdminDtosAdminSystemSettingsDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesAdminDtosAdminSystemSettingsDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesAdminDtosAdminSystemSettingsDto;
}

