/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAgentRolesDtosOptionItemDto } from './aiAdminServicesAgentRolesDtosOptionItemDto.model';


export interface AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosOptionItemDto { 
    code?: number;
    msg?: string | null;
    data?: Array<AiAdminServicesAgentRolesDtosOptionItemDto> | null;
}

