/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesRbacDtosRoleDto { 
    id?: number;
    name?: string | null;
    code?: string | null;
    remark?: string | null;
    status?: number;
    sort?: number;
    createDate?: string | null;
}

