/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminControllersRuntimeStatusDto } from './aiAdminControllersRuntimeStatusDto.model';


export interface AiAdminInfrastructureResultAiAdminControllersRuntimeStatusDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminControllersRuntimeStatusDto;
}

