/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesMemoryDtosMemoryWriteConfigDto } from './aiAdminServicesMemoryDtosMemoryWriteConfigDto.model';
import { AiAdminServicesMemoryDtosMemoryRetrievalConfigDto } from './aiAdminServicesMemoryDtosMemoryRetrievalConfigDto.model';


export interface AiAdminServicesMemoryDtosMemoryLibraryDto { 
    id?: string | null;
    userId?: number | null;
    agentId?: string | null;
    code?: string | null;
    name?: string | null;
    description?: string | null;
    status?: number | null;
    isDefault?: number | null;
    entityScope?: string | null;
    memoryModelId?: string | null;
    retrievalConfig?: AiAdminServicesMemoryDtosMemoryRetrievalConfigDto;
    writeConfig?: AiAdminServicesMemoryDtosMemoryWriteConfigDto;
    sort?: number | null;
    creator?: number | null;
    createdAt?: string | null;
    updater?: number | null;
    updatedAt?: string | null;
}

