/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto } from './aiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesRuntimeExecutionDtosTtsSynthesisResponseDto;
}

