/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto } from './aiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto.model';


export interface AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminInfrastructurePageDataAiAdminServicesBillingDtosBillingOrderItemDto;
}

