/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesDeviceDtosDeviceManualAddDto { 
    agentRoleId?: string | null;
    agentRoleReleaseId?: string | null;
    board?: string | null;
    appVersion?: string | null;
    macAddress?: string | null;
}

