/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesMemoryDtosMemorySearchHitDto { 
    id?: string | null;
    entityId?: string | null;
    sessionId?: string | null;
    ruleId?: string | null;
    recordType?: string | null;
    title?: string | null;
    content?: string | null;
    summary?: string | null;
    keywords?: any | null;
    payloadJson?: any | null;
    embeddingModelId?: string | null;
    embeddingDimension?: number;
    hasEmbedding?: boolean;
    importance?: number | null;
    isPinned?: number | null;
    score?: number;
    expiresAt?: string | null;
    updatedAt?: string | null;
}

