/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesRbacDtosRoleDto } from './aiAdminServicesRbacDtosRoleDto.model';


export interface AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesRbacDtosRoleDto { 
    code?: number;
    msg?: string | null;
    data?: Array<AiAdminServicesRbacDtosRoleDto> | null;
}

