/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAgentRolesDtosAgentRoleKnowledgeBindingDto { 
    id?: number | null;
    datasetId?: string | null;
    datasetName?: string | null;
    sort?: number | null;
    enabled?: boolean | null;
    topK?: number | null;
    minScore?: number | null;
    rerankEnabled?: boolean | null;
    maxChunks?: number | null;
}

