/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesAdminDtosAdminSystemLogSettingsDto { 
    logFormat?: string | null;
    logFormatFile?: string | null;
    logLevel?: string | null;
    logDir?: string | null;
    logFile?: string | null;
    dataDir?: string | null;
}

