/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosRuntimeSignalDto } from './aiAdminInfrastructurePageDataAiAdminServicesMemoryDtosRuntimeSignalDto.model';


export interface AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesMemoryDtosRuntimeSignalDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminInfrastructurePageDataAiAdminServicesMemoryDtosRuntimeSignalDto;
}

