/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesKnowledgeDtosListVoDto } from './aiAdminServicesKnowledgeDtosListVoDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesKnowledgeDtosListVoDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesKnowledgeDtosListVoDto;
}

