/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAgentRolesDtosActionRuleDto } from './aiAdminServicesAgentRolesDtosActionRuleDto.model';


export interface AiAdminInfrastructureResultSystemCollectionsGenericListAiAdminServicesAgentRolesDtosActionRuleDto { 
    code?: number;
    msg?: string | null;
    data?: Array<AiAdminServicesAgentRolesDtosActionRuleDto> | null;
}

