/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAuthDtosPubConfigDto } from './aiAdminServicesAuthDtosPubConfigDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesAuthDtosPubConfigDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesAuthDtosPubConfigDto;
}

