/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesAdminDtosAdminPageUserVo } from './aiAdminServicesAdminDtosAdminPageUserVo.model';


export interface AiAdminInfrastructurePageDataAiAdminServicesAdminDtosAdminPageUserVo { 
    total?: number;
    list?: Array<AiAdminServicesAdminDtosAdminPageUserVo> | null;
}

