/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesDeviceDtosDeviceProvisioningCredentialDto } from './aiAdminServicesDeviceDtosDeviceProvisioningCredentialDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesDeviceDtosDeviceProvisioningCredentialDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesDeviceDtosDeviceProvisioningCredentialDto;
}

