/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesMemoryDtosRuntimeSignalDto { 
    id?: string | null;
    signalType?: string | null;
    signalCode?: string | null;
    severity?: string | null;
    status?: string | null;
    userId?: number | null;
    deviceId?: string | null;
    agentRoleId?: string | null;
    sessionId?: string | null;
    sourceRunId?: string | null;
    sourceText?: string | null;
    payloadJson?: string | null;
    scheduledAt?: string | null;
    processedAt?: string | null;
    dedupeKey?: string | null;
    retryCount?: number;
    errorMessage?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}

