/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminServicesBindingConfigsDtosBindingConfigDto } from './aiAdminServicesBindingConfigsDtosBindingConfigDto.model';


export interface AiAdminInfrastructureResultAiAdminServicesBindingConfigsDtosBindingConfigDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminServicesBindingConfigsDtosBindingConfigDto;
}

