/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAdminServicesBillingDtosBillingSummaryDto { 
    userId?: number;
    username?: string | null;
    mobile?: string | null;
    subscriptionId?: string | null;
    subscriptionStatus?: string | null;
    planId?: string | null;
    planCode?: string | null;
    planName?: string | null;
    periodId?: string | null;
    periodKey?: string | null;
    periodStartAt?: string | null;
    periodEndAt?: string | null;
    totalTokens?: number;
    consumedTokens?: number;
    remainingTokens?: number;
    remainingRatio?: number;
    isLowBalance?: boolean;
    isExhausted?: boolean;
}

