/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeFilesDto } from './aiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeFilesDto.model';


export interface AiAdminInfrastructureResultAiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeFilesDto { 
    code?: number;
    msg?: string | null;
    data?: AiAdminInfrastructurePageDataAiAdminServicesKnowledgeDtosKnowledgeFilesDto;
}

