/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsTimingDto.model';
import { VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto } from './voloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto.model';
import { VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto } from './voloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationGlobalFeatureConfigurationDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationGlobalFeatureConfigurationDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsClockDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto.model';


export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationConfigurationDto { 
    localization?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDto;
    auth?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto;
    setting?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDto;
    currentUser?: VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto;
    features?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDto;
    globalFeatures?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: VoloAbpAspNetCoreMvcMultiTenancyMultiTenancyInfoDto;
    currentTenant?: VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto;
    timing?: VoloAbpAspNetCoreMvcApplicationConfigurationsTimingDto;
    clock?: VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto;
    objectExtensions?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto;
    extraProperties?: { [key: string]: any; } | null;
}

