/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpHttpModelingControllerInterfaceApiDescriptionModel } from './voloAbpHttpModelingControllerInterfaceApiDescriptionModel.model';
import { VoloAbpHttpModelingActionApiDescriptionModel } from './voloAbpHttpModelingActionApiDescriptionModel.model';


export interface VoloAbpHttpModelingControllerApiDescriptionModel { 
    controllerName?: string | null;
    controllerGroupName?: string | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: string | null;
    type?: string | null;
    interfaces?: Array<VoloAbpHttpModelingControllerInterfaceApiDescriptionModel> | null;
    actions?: { [key: string]: VoloAbpHttpModelingActionApiDescriptionModel; } | null;
}

