/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpNameValue } from './voloAbpNameValue.model';
import { VoloAbpLocalizationLanguageInfo } from './voloAbpLocalizationLanguageInfo.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto.model';


export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDto { 
    values?: { [key: string]: { [key: string]: string; }; } | null;
    resources?: { [key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto; } | null;
    languages?: Array<VoloAbpLocalizationLanguageInfo> | null;
    currentCulture?: VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto;
    defaultResourceName?: string | null;
    languagesMap?: { [key: string]: Array<VoloAbpNameValue>; } | null;
    languageFilesMap?: { [key: string]: Array<VoloAbpNameValue>; } | null;
}

