/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpHttpModelingPropertyApiDescriptionModel } from './voloAbpHttpModelingPropertyApiDescriptionModel.model';


export interface VoloAbpHttpModelingTypeApiDescriptionModel { 
    baseType?: string | null;
    isEnum?: boolean;
    enumNames?: Array<string> | null;
    enumValues?: Array<any> | null;
    genericArguments?: Array<string> | null;
    properties?: Array<VoloAbpHttpModelingPropertyApiDescriptionModel> | null;
}

