/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpHttpModelingTypeApiDescriptionModel } from './voloAbpHttpModelingTypeApiDescriptionModel.model';
import { VoloAbpHttpModelingModuleApiDescriptionModel } from './voloAbpHttpModelingModuleApiDescriptionModel.model';


export interface VoloAbpHttpModelingApplicationApiDescriptionModel { 
    modules?: { [key: string]: VoloAbpHttpModelingModuleApiDescriptionModel; } | null;
    types?: { [key: string]: VoloAbpHttpModelingTypeApiDescriptionModel; } | null;
}

