/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto.model';


export interface VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto { 
    displayName?: string | null;
    englishName?: string | null;
    threeLetterIsoLanguageName?: string | null;
    twoLetterIsoLanguageName?: string | null;
    isRightToLeft?: boolean;
    cultureName?: string | null;
    name?: string | null;
    nativeName?: string | null;
    dateTimeFormat?: VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto;
}

