/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpHttpModelingControllerApiDescriptionModel } from './voloAbpHttpModelingControllerApiDescriptionModel.model';


export interface VoloAbpHttpModelingModuleApiDescriptionModel { 
    rootPath?: string | null;
    remoteServiceName?: string | null;
    controllers?: { [key: string]: VoloAbpHttpModelingControllerApiDescriptionModel; } | null;
}

