/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpHttpModelingInterfaceMethodApiDescriptionModel } from './voloAbpHttpModelingInterfaceMethodApiDescriptionModel.model';


export interface VoloAbpHttpModelingControllerInterfaceApiDescriptionModel { 
    type?: string | null;
    name?: string | null;
    methods?: Array<VoloAbpHttpModelingInterfaceMethodApiDescriptionModel> | null;
}

