/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto { 
    texts?: { [key: string]: string; } | null;
    baseResources?: Array<string> | null;
}

