/**
 * AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto.model';
import { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto.model';


export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDto { 
    resources?: { [key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto; } | null;
    currentCulture?: VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto;
}

